import { CommonModule } from "@angular/common";
import { Component, effect, signal, untracked } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { PaiseInrPipe } from "../../core/paise-inr.pipe";
import { OwnerAppointmentServiceOption } from "./owner-appointments.models";
import { OwnerAppService, OwnerBundleDeal, OwnerGiftCard } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";

@Component({ standalone: true, imports: [CommonModule, FormsModule, PaiseInrPipe], template: `
<article class="ops-page" [attr.aria-busy]="loading()"><header class="ops-header"><div><p class="ops-eyebrow">Commerce tools</p><h1>Gift Cards & Bundles</h1><p>Create, redeem and manage gift cards and service bundle offers.</p></div><button class="ops-button" (click)="load()" [disabled]="loading()">{{loading()?'Refreshing...':'Refresh'}}</button></header>
@if(error()){<p class="ops-notice error" role="alert">{{error()}}</p>}
<section class="commerce-grid"><form class="ops-panel commerce-form" (ngSubmit)="createGiftCard()"><header class="ops-panel-head"><h2>New gift card</h2></header><label class="ops-field"><span>Purchaser</span><input name="purchaser" [(ngModel)]="gift.purchaserName"></label><label class="ops-field"><span>Recipient</span><input name="recipient" [(ngModel)]="gift.recipientName"></label><label class="ops-field"><span>Recipient phone</span><input name="recipientPhone" [(ngModel)]="gift.recipientPhone"></label><label class="ops-field"><span>Value</span><input type="number" min="1" step="1" name="giftValue" [ngModel]="gift.initialValuePaise/100" (ngModelChange)="gift.initialValuePaise=paise($event)"></label><label class="ops-field"><span>Expires</span><input type="date" name="giftExpiry" [(ngModel)]="gift.expiresAt"></label><button class="ops-button primary" [disabled]="saving()">Create gift card</button></form>
<form class="ops-panel commerce-form" (ngSubmit)="createBundle()"><header class="ops-panel-head"><h2>New bundle</h2></header><label class="ops-field"><span>Name</span><input name="bundleName" required [(ngModel)]="bundle.name"></label><label class="ops-field"><span>Description</span><input name="bundleDescription" [(ngModel)]="bundle.description"></label><label class="ops-field"><span>Service</span><select name="bundleService" required [(ngModel)]="bundle.serviceId"><option value="">Choose service</option>@for(service of services();track service.id){<option [value]="service.id">{{service.name}} · {{service.pricePaise|paiseInr}}</option>}</select></label><label class="ops-field"><span>Quantity</span><input type="number" min="1" name="bundleQty" [(ngModel)]="bundle.quantity"></label><label class="ops-field"><span>Bundle price</span><input type="number" min="0" step="1" name="bundlePrice" [ngModel]="bundle.pricePaise/100" (ngModelChange)="bundle.pricePaise=paise($event)"></label><button class="ops-button primary" [disabled]="saving()||!services().length">Create bundle</button></form></section>
<section class="commerce-grid"><section class="ops-panel"><header class="ops-panel-head"><h2>Gift cards</h2><span>{{giftCards().length}}</span></header><div class="ops-cards always">@for(card of giftCards();track card.id){<article class="ops-card static"><div><h3>{{card.code}}</h3><span class="ops-status">{{card.status}}</span></div><p>{{card.recipientName||'No recipient'}} · {{card.recipientPhone||'No phone'}}</p><small>{{card.balancePaise|paiseInr}} balance of {{card.initialValuePaise|paiseInr}}</small><div class="commerce-actions"><button class="ops-button" (click)="redeem(card)" [disabled]="card.status!=='active'">Redeem</button><button class="ops-button" (click)="setGiftStatus(card, card.status==='active'?'void':'active')">{{card.status==='active'?'Void':'Reactivate'}}</button></div></article>}@empty{<p class="ops-state">No gift cards yet.</p>}</div></section>
<section class="ops-panel"><header class="ops-panel-head"><h2>Bundles</h2><span>{{bundles().length}}</span></header><div class="ops-cards always">@for(item of bundles();track item.id){<article class="ops-card static"><div><h3>{{item.name}}</h3><span class="ops-status">{{item.status}}</span></div><p>{{item.description||'No description'}}</p><small>{{item.pricePaise|paiseInr}} · {{item.items.length}} service lines</small><button class="ops-button" (click)="setBundleStatus(item, item.status==='active'?'paused':'active')">{{item.status==='active'?'Pause':'Activate'}}</button></article>}@empty{<p class="ops-state">No bundles yet.</p>}</div></section></section></article>
`, styleUrls: ["./owner-shell.styles.css", "./owner-operations.css"], styles: [`.commerce-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.commerce-form{display:grid;gap:12px}.ops-cards.always{display:grid;gap:10px}.ops-card.static{text-align:left}.commerce-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:760px){.commerce-grid{grid-template-columns:1fr}}`] })
export class OwnerCommercePage { readonly loading=signal(false); readonly saving=signal(false); readonly error=signal(""); readonly giftCards=signal<OwnerGiftCard[]>([]); readonly bundles=signal<OwnerBundleDeal[]>([]); readonly services=signal<OwnerAppointmentServiceOption[]>([]); gift={purchaserName:"",recipientName:"",recipientPhone:"",initialValuePaise:100000,expiresAt:""}; bundle={name:"",description:"",serviceId:"",quantity:1,pricePaise:0}; constructor(private api:OwnerAppService, readonly context:OwnerContextService){effect(()=>{const branch=context.selectedBranchId();untracked(()=>{void branch;void this.load();});});} async load(){this.loading.set(true);this.error.set("");try{const [g,b,s]=await Promise.all([this.api.ownerGiftCards(),this.api.ownerBundles(),this.api.appointmentServices(this.context.selectedBranchId()||"all")]);this.giftCards.set(g.items);this.bundles.set(b.items);this.services.set(s.items);}catch{this.error.set("Commerce data could not be loaded.");}finally{this.loading.set(false);}} async createGiftCard(){this.saving.set(true);try{await this.api.createOwnerGiftCard({...this.gift,expiresAt:this.gift.expiresAt?`${this.gift.expiresAt}T00:00:00.000Z`:undefined});this.gift={purchaserName:"",recipientName:"",recipientPhone:"",initialValuePaise:100000,expiresAt:""};await this.load();}catch{this.error.set("Gift card could not be created.");}finally{this.saving.set(false);}} async createBundle(){if(!this.bundle.name.trim()||!this.bundle.serviceId.trim())return;this.saving.set(true);try{await this.api.createOwnerBundle({name:this.bundle.name,description:this.bundle.description,items:[{serviceId:this.bundle.serviceId,quantity:this.bundle.quantity}],pricePaise:this.bundle.pricePaise});this.bundle={name:"",description:"",serviceId:"",quantity:1,pricePaise:0};await this.load();}catch{this.error.set("Bundle could not be created.");}finally{this.saving.set(false);}} async redeem(card:OwnerGiftCard){const amount=Number(prompt("Redeem amount in rupees", String(card.balancePaise/100))||0);if(!amount)return;await this.api.redeemOwnerGiftCard(card.id,{amountPaise:this.paise(amount)});await this.load();} async setGiftStatus(card:OwnerGiftCard,status:string){await this.api.setOwnerGiftCardStatus(card.id,status);await this.load();} async setBundleStatus(item:OwnerBundleDeal,status:string){await this.api.setOwnerBundleStatus(item.id,status);await this.load();} paise(v:string|number){return Math.round((Number(v)||0)*100);} }
