import { Component, ElementRef, OnDestroy, ViewChild, computed, effect, signal, untracked } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerChatConversation, OwnerChatMessage, OwnerChatReceiptUpdate, OwnerOperationsMetadata, OwnerOperationsPage } from "./owner-operations.models";
import { OwnerStaff } from "./owner-people.models";

@Component({
  standalone: true,
  imports: [FormsModule],
  template: `
    <article class="ops-page" [attr.aria-busy]="loading()">
      <header class="ops-header"><div><p class="ops-eyebrow">Branch conversations</p><h1>Team chat</h1><p>Live team and private-owner conversations for your assigned branches.</p></div>
        @if (!blockingError()) { <div class="ops-actions"><button class="ops-button" type="button" (click)="showCreate.set(!showCreate())">{{ showCreate() ? 'Cancel' : 'New conversation' }}</button><button class="ops-button" type="button" [disabled]="loading()" (click)="load()">{{ loading() ? 'Refreshing…' : 'Refresh' }}</button></div> }
      </header>
      @if (messageError()) { <p class="ops-notice error" role="alert">{{ messageError() }}</p> }
      @if (metadata()?.partial) { <p class="ops-notice">Conversation search covers titles and branches. Message-body search is not available.</p> }
      <section class="ops-toolbar">
        <label class="ops-field ops-search"><span>Search conversations</span><input type="search" [ngModel]="search()" (ngModelChange)="searchChanged($event)" placeholder="Conversation or branch" />@if (search()) { <button type="button" (click)="clearSearch()" aria-label="Clear conversation search">×</button> }</label>
        <label class="ops-field"><span>Branch filter</span><select [ngModel]="context.selectedBranchId()" (ngModelChange)="branchChanged($event)"><option value="">All accessible branches</option>@for (branch of context.branches(); track branch.id) { <option [value]="branch.id">{{ branch.name }}</option> }</select></label>
        <div class="ops-field"><span>Unread on page</span><strong>{{ unreadTotal() }}</strong></div><div class="ops-field"><span>Updates</span><strong>{{ connectionState() }}</strong></div>
      </section>
      @if (showCreate()) {
        <section class="ops-toolbar" aria-label="New private conversation">
          <label class="ops-field"><span>Target Branch</span><select [ngModel]="createBranchId()" (ngModelChange)="createBranchId.set($event)"><option value="">All branches</option>@for (branch of context.branches(); track branch.id) { <option [value]="branch.id">{{ branch.name }}</option> }</select></label>
          <label class="ops-field"><span>Staff member</span><select [(ngModel)]="newStaffId"><option value="">Select staff member</option>@for (staff of filteredCreateStaff(); track staff.id) { <option [value]="staff.id">{{ staff.fullName }} ({{ staff.designation || 'Staff' }}) · {{ staff.branchName || 'Assigned branch' }}</option> }</select></label>
          <button class="ops-button primary" type="button" [disabled]="creating() || !newStaffId" (click)="createConversation()">{{ creating() ? 'Opening…' : 'Open private chat' }}</button>
        </section>
      }
      @if (loading() && !conversations().length) { <div class="ops-skeleton"><i></i><i></i><i></i><i></i></div> }
      @else if (blockingError()) { <div class="ops-state" role="alert"><span>!</span><h2>Team chat unavailable</h2><p>{{ blockingError() }}</p><button class="ops-button" (click)="load()">Try again</button></div> }
      @else if (!conversations().length) { <div class="ops-state"><span>—</span><h2>No conversations</h2><p>No permitted conversations match the current branch and search.</p></div> }
      @else {
        <section class="chat-shell"><aside class="chat-list" aria-label="Conversations"><header class="ops-panel-head"><h2>Conversations</h2><span>Loaded {{ conversations().length }} of {{ page()?.total || 0 }}</span></header>
          @for (item of conversations(); track item.id + '-' + item.branchId) { <button type="button" [class.selected]="selected()?.id === item.id && selected()?.branchId === item.branchId" (click)="open(item)"><strong>{{ item.title }} @if (item.unreadCount) { <b>{{ item.unreadCount }}</b> }</strong><span>{{ item.branchName }} · {{ item.type === 'team' ? 'Team' : 'Private owner' }}</span><small>{{ item.lastMessageAt ? dateTime(item.lastMessageAt) : 'No messages yet' }}</small></button> }
          @if (page(); as pagination) { @if (pagination.totalPages > 1) { <nav class="pager" aria-label="Conversation pages"><button type="button" [disabled]="pagination.page <= 1 || loading()" (click)="go(-1)">Previous</button><span>Page {{ pagination.page }} of {{ pagination.totalPages }}</span><button type="button" [disabled]="!pagination.hasMore || loading()" (click)="go(1)">Next</button></nav> } }
        </aside>
        <section class="chat-thread" [attr.aria-label]="selected()?.title || 'Conversation'">@if (selected(); as chat) { <header><button class="ops-button" type="button" (click)="closeThread()" aria-label="Back to conversations">←</button><h2>{{ chat.title }}</h2><p>{{ chat.branchName }} · Branch scoped</p></header>
          <div class="chat-messages" #messageList aria-live="polite">@if (messagesLoading()) { <div class="ops-skeleton"><i></i><i></i></div> } @else if (messagesError()) { <div class="ops-state"><span>!</span><h2>Messages unavailable</h2><p>{{ messagesError() }}</p><button class="ops-button" (click)="open(chat)">Retry</button></div> } @else { @for (item of messages(); track item.id; let index = $index) { @if (showDate(index)) { <span class="chat-date">{{ date(item.createdAt) }}</span> }<article class="chat-message" [class.own]="item.senderUserId === owner.user()?.id"><strong>{{ item.senderName || 'Team member' }}</strong><p>{{ item.body }}</p><small>{{ time(item.createdAt) }}@if (item.senderUserId === owner.user()?.id && item.receipt.readCount) { · Read {{ item.receipt.readCount }} }</small></article> } @empty { <div class="ops-state"><span>—</span><h2>No messages yet</h2><p>Start this branch conversation below.</p></div> } }</div>
          <form class="ops-composer" (ngSubmit)="send()"><label for="owner-chat-message">Message</label><textarea id="owner-chat-message" name="message" [(ngModel)]="draft" maxlength="4000" placeholder="Write a message" [disabled]="sending()"></textarea><button class="ops-button primary" type="submit" [disabled]="sending() || !draft.trim()">{{ sending() ? 'Sending…' : 'Send' }}</button></form>
        } @else { <div class="ops-state"><span>↗</span><h2>Select a conversation</h2><p>Choose a branch conversation to read and reply.</p></div> }</section></section>
      }
    </article>`,
  styleUrls: ["./owner-shell.styles.css", "./owner-operations.css"]
})
export class OwnerChatsLivePage implements OnDestroy {
  @ViewChild("messageList") messageList?: ElementRef<HTMLElement>;
  readonly conversations = signal<OwnerChatConversation[]>([]); readonly page = signal<OwnerOperationsPage | null>(null); readonly metadata = signal<OwnerOperationsMetadata | null>(null);
  readonly loading = signal(true); readonly blockingError = signal(""); readonly messageError = signal(""); readonly search = signal(""); readonly debouncedSearch = signal("");
  readonly selected = signal<OwnerChatConversation | null>(null); readonly messages = signal<OwnerChatMessage[]>([]); readonly messagesLoading = signal(false); readonly messagesError = signal(""); readonly sending = signal(false);
  readonly staffOptions = signal<OwnerStaff[]>([]); readonly showCreate = signal(false); readonly creating = signal(false); readonly connectionState = signal<"live" | "polling" | "connecting">("connecting");
  readonly createBranchId = signal("");
  readonly filteredCreateStaff = computed(() => {
    const selectedBranch = this.createBranchId() || this.context.selectedBranchId();
    if (!selectedBranch || selectedBranch === "all") return this.staffOptions();
    return this.staffOptions().filter((item) => item.branchId === selectedBranch);
  });
  readonly unreadTotal = computed(() => this.conversations().reduce((sum, item) => sum + item.unreadCount, 0));
  draft = ""; newStaffId = "";
  private requestId = 0; private messageRequestId = 0; private socketGeneration = 0; private destroyed = false;
  private timer?: ReturnType<typeof setTimeout>; private pollTimer: ReturnType<typeof setInterval>; private reconnectTimer?: ReturnType<typeof setTimeout>; private readonly sockets = new Map<string, WebSocket>();

  constructor(readonly owner: OwnerAppService, readonly context: OwnerContextService) {
    this.pollTimer = setInterval(() => void this.poll(), 15000);
    effect(() => { const branch = context.selectedBranchId(); const branchIds = context.branches().map((item) => item.id).join("|"); untracked(() => { void branchIds; this.closeThread(); this.page.set(null); void this.load(); void this.loadStaff(); void this.connectRealtime(branch); }); });
  }
  ngOnDestroy(): void { this.destroyed = true; if (this.timer) clearTimeout(this.timer); if (this.reconnectTimer) clearTimeout(this.reconnectTimer); clearInterval(this.pollTimer); this.closeSockets(); this.requestId++; this.messageRequestId++; }
  searchChanged(value: string): void { this.search.set(value); if (this.timer) clearTimeout(this.timer); this.timer = setTimeout(() => { this.debouncedSearch.set(value.trim()); this.page.set(null); void this.load(); }, 350); }
  clearSearch(): void { this.search.set(""); this.debouncedSearch.set(""); this.page.set(null); void this.load(); }
  branchChanged(branchId: string): void { this.context.selectBranch(branchId); }
  go(delta: number): void { const current = this.page(); if (!current) return; this.page.set({ ...current, page: current.page + delta }); void this.load(); }
  async load(background = false): Promise<void> { const request = ++this.requestId, had = this.conversations().length > 0; if (!background) this.loading.set(true); this.messageError.set(""); try { const result = await this.owner.ownerChats({ branchId: this.context.selectedBranchId() || "all", page: this.page()?.page || 1, pageSize: 30, search: this.debouncedSearch() }); if (request !== this.requestId) return; this.conversations.set(result.items); this.page.set(result.page); this.metadata.set(result.metadata); this.blockingError.set(""); this.context.markSuccessfulRefresh(); if (!this.selected() && result.items.length > 0) { void this.open(result.items[0]); } } catch { if (request !== this.requestId) return; if (had) this.messageError.set("Refresh failed. Previously loaded conversations remain visible."); else this.blockingError.set("Solastio could not load permitted branch conversations."); } finally { if (request === this.requestId) this.loading.set(false); } }
  async open(chat: OwnerChatConversation): Promise<void> { this.selected.set(chat); this.messages.set([]); this.messagesError.set(""); this.messagesLoading.set(true); const request = ++this.messageRequestId; try { const result = await this.owner.ownerChatMessages(chat.id, chat.branchId); if (request === this.messageRequestId) { this.messages.set(result.items); await this.markReceipts(chat, result.items, "read"); setTimeout(() => this.scrollEnd()); } } catch { if (request === this.messageRequestId) this.messagesError.set("Messages could not be loaded for this branch conversation."); } finally { if (request === this.messageRequestId) this.messagesLoading.set(false); } }
  closeThread(): void { this.messageRequestId++; this.selected.set(null); this.messages.set([]); this.messagesError.set(""); this.draft = ""; }
  async send(): Promise<void> { const chat = this.selected(), body = this.draft.trim(); if (!chat || !body || this.sending()) return; this.sending.set(true); this.messageError.set(""); try { const message = await this.owner.sendOwnerChatMessage(chat.id, chat.branchId, body, crypto.randomUUID()); this.messages.update((items) => this.dedupe([...items, message])); this.draft = ""; setTimeout(() => this.scrollEnd()); await this.load(true); } catch { this.messageError.set("Message was not sent. Your draft remains available."); } finally { this.sending.set(false); } }
  async createConversation(): Promise<void> { const staff = this.staffOptions().find((item) => item.id === this.newStaffId); if (!staff || this.creating()) return; const branchId = staff.branchId || this.createBranchId() || this.context.selectedBranchId() || (this.context.branches()[0]?.id || ""); if (!branchId) return; this.creating.set(true); this.messageError.set(""); try { const conversation = await this.owner.createOwnerPrivateChat(branchId, staff.id, crypto.randomUUID()); this.showCreate.set(false); this.newStaffId = ""; this.page.set(null); await this.load(); await this.open(conversation); } catch { this.messageError.set(this.owner.error() || "Private conversation could not be opened."); } finally { this.creating.set(false); } }
  showDate(index: number): boolean { return index === 0 || this.date(this.messages()[index - 1].createdAt) !== this.date(this.messages()[index].createdAt); }
  date(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(this.context.effectiveLocale(), { dateStyle: "medium", timeZone: this.context.effectiveTimezone() }).format(date); }
  time(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(this.context.effectiveLocale(), { hour: "numeric", minute: "2-digit", timeZone: this.context.effectiveTimezone() }).format(date); }
  dateTime(value: string): string { return this.context.formatDateTime(value); }

  private async loadStaff(): Promise<void> { try { const items: OwnerStaff[] = []; let offset = 0; do { const result = await this.owner.ownerStaff({ branchId: "all", offset, limit: 200, status: "active" }); items.push(...result.items); if (!result.page?.hasMore) break; offset += result.page.limit; } while (!this.destroyed); if (!this.destroyed) this.staffOptions.set(items); } catch { this.staffOptions.set([]); } }
  private async poll(): Promise<void> { if (this.destroyed) return; if (![...this.sockets.values()].some((socket) => socket.readyState === WebSocket.OPEN)) this.connectionState.set("polling"); await this.load(true); const chat = this.selected(); if (chat) { try { const result = await this.owner.ownerChatMessages(chat.id, chat.branchId); if (this.selected()?.id === chat.id) { this.messages.set(this.dedupe(result.items)); await this.markReceipts(chat, result.items, "read"); } } catch { /* The next poll or socket event retries. */ } } }
  private async connectRealtime(selectedBranchId: string): Promise<void> { const generation = ++this.socketGeneration; this.closeSockets(); const branchIds = selectedBranchId ? [selectedBranchId] : this.context.branches().map((branch) => branch.id); if (!branchIds.length || this.destroyed) { this.connectionState.set("polling"); return; } this.connectionState.set("connecting"); await Promise.all(branchIds.map(async (branchId) => { try { const url = await this.owner.realtimeSocketTicketUrl(branchId); if (this.destroyed || generation !== this.socketGeneration) return; const socket = new WebSocket(url); this.sockets.set(branchId, socket); socket.onopen = () => this.connectionState.set("live"); socket.onmessage = (event) => this.handleRealtime(branchId, event.data); socket.onerror = () => socket.close(); socket.onclose = () => { if (this.sockets.get(branchId) === socket) this.sockets.delete(branchId); if (!this.destroyed && generation === this.socketGeneration && ![...this.sockets.values()].some((item) => item.readyState === WebSocket.OPEN)) { this.connectionState.set("polling"); this.scheduleReconnect(); } }; } catch { if (!this.destroyed) { this.connectionState.set("polling"); this.scheduleReconnect(); } } })); }
  private handleRealtime(branchId: string, raw: unknown): void { let frame: { type?: string; payload?: { message?: OwnerChatMessage; conversationId?: string; receipts?: OwnerChatReceiptUpdate[] } } = {}; try { frame = JSON.parse(String(raw)); } catch { return; } if (frame.type === "team-chat.receipt-updated" && frame.payload?.conversationId === this.selected()?.id) { this.mergeReceipts(frame.payload?.receipts || []); return; } if (frame.type === "team-chat.conversation-created") { void this.load(true); return; } if (!["staff-self.chat_message", "team-chat.private-message"].includes(frame.type || "") || !frame.payload?.message) return; const message = frame.payload.message; const chat = this.conversations().find((item) => item.id === message.conversationId && item.branchId === branchId); if (message.senderUserId !== this.owner.user()?.id && chat) void this.markReceipts(chat, [message], this.selected()?.id === chat.id && document.visibilityState === "visible" ? "read" : "delivered"); if (this.selected()?.id === message.conversationId && this.selected()?.branchId === branchId) { this.messages.update((items) => this.dedupe([...items, message])); setTimeout(() => this.scrollEnd()); } void this.load(true); }
  private async markReceipts(chat: OwnerChatConversation, messages: OwnerChatMessage[], status: "delivered" | "read"): Promise<void> { const ids = messages.filter((message) => message.senderUserId !== this.owner.user()?.id).map((message) => message.id); if (!ids.length) return; try { const result = await this.owner.markOwnerChatReceipts(chat.id, chat.branchId, ids.slice(-200), status); this.mergeReceipts(result.receipts); if (status === "read") this.conversations.update((items) => items.map((item) => item.id === chat.id && item.branchId === chat.branchId ? { ...item, unreadCount: 0 } : item)); } catch { /* Receipt writes are idempotent and retry on poll. */ } }
  private mergeReceipts(receipts: OwnerChatReceiptUpdate[]): void { const updates = new Map(receipts.map((receipt) => [receipt.messageId, receipt])); this.messages.update((items) => items.map((message) => { const receipt = updates.get(message.id); return receipt ? { ...message, receipt: { deliveredCount: Math.max(message.receipt.deliveredCount, receipt.deliveredCount), readCount: Math.max(message.receipt.readCount, receipt.readCount) } } : message; })); }
  private dedupe(messages: OwnerChatMessage[]): OwnerChatMessage[] { return [...new Map(messages.map((message) => [message.id, message])).values()].sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
  private scheduleReconnect(): void { if (this.reconnectTimer) clearTimeout(this.reconnectTimer); this.reconnectTimer = setTimeout(() => void this.connectRealtime(this.context.selectedBranchId()), 3000); }
  private closeSockets(): void { for (const socket of this.sockets.values()) { socket.onclose = null; socket.close(); } this.sockets.clear(); }
  private scrollEnd(): void { const element = this.messageList?.nativeElement; if (element) element.scrollTop = element.scrollHeight; }
}
