import { Component, OnInit, signal } from "@angular/core";
import { StaffAppService, StaffEnterpriseOs } from "../../core/staff-app.service";
import { PaiseInrPipe } from "../../core/paise-inr.pipe";
import { StaffPageStateComponent } from "./staff-page-state.component";

@Component({ standalone: true, imports: [PaiseInrPipe, StaffPageStateComponent], template: `
  <section class="page"><header class="page-head"><div><p class="eyebrow">Leaderboard</p><h1>Leaderboard</h1><p>Branch-scoped performance ranking and gamification.</p></div></header>
  @if (!canReadLeaderboard()) { <section staffPageState class="notice">You do not have permission to view leaderboard data.</section> }
  @if (loading()) { <section staffPageState class="state" [loading]="true">Loading leaderboard...</section> } @if (staff.error()) { <section staffPageState class="notice">{{ staff.error() }}</section> }
  @if (canReadLeaderboard() && os(); as data) { <section class="grid four"><article class="kpi"><span>Points</span><strong>{{ data.gamification.points }}</strong></article><article class="kpi"><span>Level</span><strong>{{ data.gamification.level }}</strong></article><article class="kpi"><span>Stars</span><strong>{{ data.gamification.stars }}</strong></article><article class="kpi"><span>Streak</span><strong>{{ data.gamification.monthlyStreak }}</strong></article></section><section class="grid two"><article class="panel"><div class="panel-title"><h2>Rankings</h2><span>{{ data.leaderboard.length }}</span></div><div class="list">@for (row of data.leaderboard; track row.staffId) { <div class="row"><div class="row-main"><strong>#{{ row.rank }} {{ row.staffName }}</strong><small>{{ row.days }} tracked days</small></div><div class="row-actions"><span class="badge" [class.green]="row.isMe">{{ row.score }}/100</span>@if (canSeeRevenue()) { <span class="badge">{{ row.revenue | paiseInr }}</span> }</div></div> } @empty { <p class="empty">No ranking data available.</p> }</div></article><article class="panel"><div class="panel-title"><h2>Badges</h2><span>{{ data.gamification.badges.length }}</span></div><div class="row-actions">@for (badge of data.gamification.badges; track badge.label) { <span class="badge" [class.green]="badge.earned">{{ badge.label }}</span> }</div></article></section> }
  </section>`, styleUrls: ["./staff-app.styles.css"] })
export class StaffLeaderboardPage implements OnInit { readonly os = signal<StaffEnterpriseOs | null>(null); readonly loading = signal(false); constructor(readonly staff: StaffAppService) {} ngOnInit() { if (this.canReadLeaderboard()) void this.load(); } async load() { if (!this.canReadLeaderboard()) return; const cached = this.staff.readStoredData<StaffEnterpriseOs>("enterprise-os"); if (cached) { this.os.set(cached); this.loading.set(false); } else { this.loading.set(true); } try { const data = await this.staff.enterpriseOs(); this.os.set(data); this.staff.writeStoredData("enterprise-os", data); } finally { this.loading.set(false); } } canReadLeaderboard(): boolean { return this.staff.hasPermission("read:staff"); } canSeeRevenue(): boolean { return this.staff.hasAnyPermission(["read:finance", "read:sales", "read:payments", "read:invoices"]); } }
