import { CommonModule } from "@angular/common";
import { Component, ElementRef, HostListener, OnInit, ViewChild, computed, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerAccessAdministration, OwnerAdministrationRole, OwnerAdministrationUser, OwnerPermissionItem, OwnerRoleWrite, OwnerUserWrite } from "./owner-administration.models";

type AccessDialog = "role" | "user" | "disable" | null;

@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `
<article class="adm-page" [attr.aria-busy]="loading()" [attr.inert]="dialog() ? '' : null">
  <header class="adm-hero"><div><p class="adm-eyebrow">Administration · Access</p><h1>Give the right access. Keep control.</h1><p>Manage Staff App access from Aura’s live permission catalogue. Changes apply only within branches assigned to your owner account.</p></div><div class="adm-actions"><button class="adm-button" type="button" [disabled]="loading()" (click)="load(true)">↻ Refresh</button><button class="adm-button primary" type="button" [disabled]="loading()||!data()?.capabilities?.createRole" (click)="openRole(null,false,$event)">＋ New role</button><button class="adm-button" type="button" [disabled]="loading()||!data()?.capabilities?.createUser" (click)="openUser(null,$event)">＋ Administrative user</button></div></header>
  @if(message()){<p class="adm-message" [class.error]="messageError()" [attr.role]="messageError()?'alert':'status'">{{message()}}</p>}
  <div class="adm-toolbar"><div class="adm-tabs" role="tablist" aria-label="Access views" (keydown)="tabKey($event)"><button id="access-tab-roles" type="button" role="tab" aria-controls="access-panel-roles" [class.active]="view()==='roles'" [attr.aria-selected]="view()==='roles'" [attr.tabindex]="view()==='roles'?0:-1" (click)="changeView('roles')">Roles</button><button id="access-tab-users" type="button" role="tab" aria-controls="access-panel-users" [class.active]="view()==='users'" [attr.aria-selected]="view()==='users'" [attr.tabindex]="view()==='users'?0:-1" (click)="changeView('users')">Users</button></div>@if(view()==='roles'){<label class="adm-field adm-scope">Policy scope<select [ngModel]="scopeBranchId()" (ngModelChange)="changeScope($event)" [disabled]="loading()"><option value="">All branches</option>@for(branch of data()?.branches||[];track branch.id){<option [value]="branch.id">{{branch.name}}</option>}</select></label>}<label class="adm-field grow" for="access-search">Search<input id="access-search" type="search" [ngModel]="query()" (ngModelChange)="changeQuery($event)" [placeholder]="view()==='roles'?'Role name or description':'Name, email, login or role'"></label></div><p class="adm-sr-status" role="status" aria-live="polite">{{loading()?'Loading roles and access data':error()||''}}</p>
  @if(loading()&&!data()){<div class="adm-skeleton"><i></i><i></i><i></i></div>}@else if(error()&&!data()){<section class="adm-state" role="alert"><span>!</span><h2>Access catalogue unavailable</h2><p>{{error()}}</p><button class="adm-button" type="button" (click)="load()">Try again</button></section>}@else if(view()==='roles'){<div id="access-panel-roles" role="tabpanel" aria-labelledby="access-tab-roles">
    <section class="adm-layout"><section class="adm-panel"><header class="adm-panel-head"><h2>Role catalogue</h2><span>{{roles().length}} shown</span></header><div class="adm-list">@for(role of roles();track role.role){<button type="button" [class.selected]="selectedRole()?.role===role.role" (click)="selectedRole.set(role)"><span class="adm-avatar">{{role.name.charAt(0)}}</span><span><span class="adm-title-line"><strong>{{role.name}}</strong><em>{{role.kind==='system'?'System':'Custom'}}</em></span><small>{{effectiveCount(role)}} of {{allPermissionCount()}} Staff App permissions</small><small>{{sourceLabel(role)}} · {{role.activeAssignedUserCount}} active / {{role.assignedUserCount}} assigned</small></span><span class="adm-status" [attr.data-active]="role.status==='active'">{{role.status}}</span></button>}@empty{<div class="adm-state"><span>—</span><h2>No matching roles</h2><p>Try a different search.</p></div>}</div></section>
    <section class="adm-panel">@if(selectedRole();as role){<div class="adm-detail"><div class="adm-detail-hero"><div><p class="adm-eyebrow">{{role.kind==='system'?'System role':'Custom role'}} · {{sourceLabel(role)}}</p><h2>{{role.name}}</h2><p>{{role.description||'No role description recorded.'}}</p></div><div class="adm-actions">@if(role.editablePolicy){<button class="adm-button" type="button" (click)="openRole(role,false,$event)">{{role.kind==='system'?'Customize App Access':'Edit Role'}}</button>}<button class="adm-button" type="button" (click)="openRole(role,true,$event)">Duplicate</button></div></div><div class="adm-role-summary"><div><strong>{{effectiveCount(role)}} / {{allPermissionCount()}}</strong><span>Effective permissions</span></div><div><strong>{{role.assignedUserCount}}</strong><span>Assigned users</span></div><div><strong>{{role.activeAssignedUserCount}}</strong><span>Active users</span></div></div>@if(!role.editablePolicy){<p class="adm-note"><strong>Essential access is protected</strong>Owner and super administrator roles always retain full Staff App access. Their metadata and policy cannot be changed.</p>}@else if(role.policyMode==='inherited'){<p class="adm-note"><strong>Using Aura defaults</strong>This role inherits Aura’s current default policy. Customizing creates a {{scopeBranchId()?'branch':'tenant'}} override.</p>}@else{<p class="adm-note"><strong>{{sourceLabel(role)}}</strong>This role uses a saved override instead of only its inherited defaults.</p>}<div class="adm-permissions">@for(group of visibleGroups(role);track group.key){<section class="adm-permission-group"><header><h3>{{group.label}}</h3><span class="adm-status">{{grantsInGroup(role,group.key)}} granted</span></header><div>@for(item of group.items;track item.key){@if(effectiveKeys(role).includes(item.key)){<div class="adm-check"><span aria-hidden="true">✓</span><span>{{item.label}}<small *ngIf="item.sensitive">Sensitive access</small></span></div>}}</div></section>}@empty{<p class="adm-note"><strong>No Staff App access</strong>This active policy has zero effective grants.</p>}</div></div>}@else{<div class="adm-state"><span>↗</span><h2>Select a role</h2><p>Review effective permissions, source and assignment impact.</p></div>}</section></section>
  </div>}@else{<div id="access-panel-users" role="tabpanel" aria-labelledby="access-tab-users">
    <section class="adm-layout"><section class="adm-panel"><header class="adm-panel-head"><h2>Tenant users</h2><span>{{users().length}} shown</span></header><div class="adm-list">@for(user of users();track user.id){<button type="button" [class.selected]="selectedUser()?.id===user.id" (click)="selectedUser.set(user)"><span class="adm-avatar">{{user.name.charAt(0)}}</span><span><strong>{{user.name}}</strong><small>{{user.email}} · {{roleName(user.role)}}</small><small>{{user.staffId?'Linked to staff':'Administrative account · not staff-linked'}}</small></span><span class="adm-status" [attr.data-active]="user.status==='active'">{{user.status}}</span></button>}@empty{<div class="adm-state"><span>—</span><h2>No matching users</h2><p>Try a different search.</p></div>}</div></section>
    <section class="adm-panel">@if(selectedUser();as user){<div class="adm-detail"><div class="adm-detail-hero"><div><p class="adm-eyebrow">{{user.staffId?'Staff-linked login':'Administrative account'}}</p><h2>{{user.name}}</h2><p>{{user.email}} · {{user.loginId||'No login ID'}}</p></div><div class="adm-actions"><button class="adm-button" type="button" [disabled]="isCurrentOwner(user)" (click)="openUser(user,$event)">Edit access</button><button class="adm-button danger" type="button" [disabled]="isCurrentOwner(user)||user.status!=='active'" (click)="openDisable(user,$event)">Disable</button></div></div><dl class="adm-facts"><div><dt>Role</dt><dd>{{roleName(user.role)}}{{roleStatus(user.role)==='inactive'?' · Inactive':''}}</dd></div><div><dt>Status</dt><dd>{{user.status}}{{user.isLocked?' · Locked':''}}</dd></div><div><dt>Staff linkage</dt><dd>{{user.staffId?'Linked':'Not linked'}}</dd></div><div><dt>Branch access</dt><dd>{{branchNames(user.branchIds)}}</dd></div><div><dt>Active sessions</dt><dd>{{user.activeSessions}}</dd></div><div><dt>Last login</dt><dd>{{user.lastLoginAt?date(user.lastLoginAt):'Not recorded'}}</dd></div></dl>@if(roleStatus(user.role)==='inactive'){<p class="adm-note warning"><strong>Current role is inactive</strong>This account cannot use the Staff App until it is reassigned to an active role.</p>}@if(isCurrentOwner(user)){<p class="adm-note"><strong>Your owner access is protected</strong>This session cannot remove its owner role or disable itself.</p>}@else if(!user.staffId){<p class="adm-note"><strong>Not a Staff App account</strong>This user is not linked to a staff record. Provision staff login from Staff directory → Login & Role Access.</p>}@else{<p class="adm-note"><strong>Session protection</strong>Access changes increment permissionVersion and require affected users to sign in again.</p>}</div>}@else{<div class="adm-state"><span>↗</span><h2>Select a user</h2><p>Review role, staff linkage and branch scope.</p></div>}</section></section>
  </div>}
</article>
@if(dialog()){<button class="adm-backdrop" type="button" tabindex="-1" [disabled]="submitting()" (click)="close()" aria-label="Close access dialog"></button><section class="adm-dialog" role="dialog" aria-modal="true" aria-labelledby="access-dialog-title" #modal tabindex="-1"><header><div><p class="adm-eyebrow">Roles & permissions</p><h2 id="access-dialog-title">{{dialogTitle()}}</h2></div><button class="adm-close" type="button" [disabled]="submitting()" (click)="close()" aria-label="Close access dialog">×</button></header>
  @if(dialog()==='role'){<form id="access-form" class="adm-form" (ngSubmit)="saveRole()"><fieldset class="adm-form-contents" [disabled]="submitting()">
    @if(!editingRole()||duplicating()){<label class="adm-field">Display name<input name="roleName" [ngModel]="roleForm.name" (ngModelChange)="roleNameChanged($event)" required maxlength="100" autocomplete="off"></label><label class="adm-field">Start with<select name="roleTemplate" [ngModel]="templateRole()" (ngModelChange)="applyTemplate($event)"><option value="">No permissions</option>@for(role of templateRoles();track role.role){<option [value]="role.role">Copy {{role.name}}</option>}</select></label><label class="adm-advanced full"><input type="checkbox" name="advancedKey" [ngModel]="advancedKey()" (ngModelChange)="advancedKey.set($event)"><span>Advanced: set technical role key</span></label>@if(advancedKey()){<label class="adm-field full">Technical key<input name="roleKey" [(ngModel)]="roleForm.role" required pattern="[A-Za-z][A-Za-z0-9_-]{2,40}" maxlength="41" autocomplete="off"><small>Permanent after first save. Must be unique.</small></label>}}
    @if(editingRole()&&!duplicating()){<label class="adm-field">Display name<input name="roleName" [(ngModel)]="roleForm.name" [readonly]="roleBase()?.kind==='system'" required maxlength="100"></label><label class="adm-field">Technical key<input name="roleKey" [(ngModel)]="roleForm.role" readonly><small>Permanent role identifier</small></label>}
    @if(roleBase()?.kind==='custom'||!editingRole()||duplicating()){<label class="adm-field full">Description<textarea name="roleDescription" [(ngModel)]="roleForm.description" maxlength="300"></textarea></label>}@else{<p class="adm-note full"><strong>System metadata is locked</strong>Name, key and description remain managed by Aura. App access and role availability can still be customized.</p>}<label class="adm-field">Status<select name="roleStatus" [(ngModel)]="roleForm.status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
    @if(scopeBranchId()){<p class="adm-note"><strong>Branch override</strong>These permissions apply to {{branchName(scopeBranchId())}}. Role metadata remains tenant-wide.</p>}
    <div class="adm-policy-map full" aria-live="polite"><div><span>Inherited / default</span><strong>{{inheritedCount()}} permissions</strong></div><span aria-hidden="true">→</span><div><span>Effective after save</span><strong>{{roleForm.permissionKeys.length}} permissions</strong></div><em>{{roleForm.mode==='inherited'?'Aura defaults':'Saved override'}}</em></div>
    @if(roleBase()?.policyMode==='override'&&editingRole()&&!duplicating()){<div class="adm-restore full"><p><strong>Override active</strong><span>Restore the inherited Aura policy for this scope.</span></p><button class="adm-button sm" type="button" (click)="requestRestoreDefaults()" [disabled]="submitting()||!data()?.capabilities?.restoreRoleDefaults">Restore Aura Defaults</button></div>}@if(restoreWarning()){<div class="adm-confirm full" role="alertdialog" aria-labelledby="restore-title" tabindex="-1" #inlineConfirm><div><strong id="restore-title">Restore Aura defaults?</strong><span>This replaces the saved override. {{roleBase()?.assignedUserCount||0}} assigned user(s) may gain or lose access and active sessions must sign in again.</span></div><div class="adm-actions"><button class="adm-button sm" type="button" (click)="cancelInlineConfirmation()">Keep override</button><button class="adm-button sm danger" type="button" (click)="restoreDefaults()">Restore defaults</button></div></div>}
    @if(roleError()){<p class="adm-message error full" role="alert">{{roleError()}}</p>}
    @if(pendingSensitive();as item){<div class="adm-confirm full" role="alertdialog" aria-labelledby="sensitive-title" tabindex="-1" #inlineConfirm><div><strong id="sensitive-title">Grant sensitive access?</strong><span>{{item.label}} can expose or change financial information. Confirm that this role needs it.</span></div><div class="adm-actions"><button class="adm-button sm" type="button" (click)="cancelInlineConfirmation()">Cancel</button><button class="adm-button sm danger" type="button" (click)="confirmSensitive()">Grant access</button></div></div>}
    <div class="adm-permissions full"><div class="adm-all-toggle"><div><strong>Effective Staff App access</strong><span class="adm-toggle-count">{{roleForm.permissionKeys.length}} of {{allPermissionCount()}} permissions</span></div><div class="adm-actions"><button type="button" class="adm-button sm" (click)="grantAll()">Grant All</button><button type="button" class="adm-button sm danger" (click)="requestRevokeAll()">Revoke All</button></div></div>
      @if(revokeWarning()){<div class="adm-confirm" role="alert"><div><strong>Revoke all access?</strong><span>{{roleBase()?.assignedUserCount||0}} assigned user(s) will lose Staff App access and must sign in again.</span></div><div class="adm-actions"><button class="adm-button sm" type="button" (click)="revokeWarning.set(false)">Keep access</button><button class="adm-button sm danger" type="button" (click)="confirmRevokeAll()">Confirm revoke</button></div></div>}
      @for(group of data()?.permissionGroups||[];track group.key){<section class="adm-permission-group"><header><label class="adm-group-toggle"><input type="checkbox" [checked]="allInGroupGranted(group.key)" [indeterminate]="someInGroupGranted(group.key)" (change)="toggleGroup(group.key)"><span><strong>{{group.label}}</strong><small>{{selectedInGroup(group.key)}} of {{group.items.length}} effective</small></span></label></header><div>@for(item of group.items;track item.key){<label class="adm-check"><input type="checkbox" [checked]="roleForm.permissionKeys.includes(item.key)" (change)="requestPermission(item)"><span>{{item.label}}<small>{{inheritedState(item.key)}}<b *ngIf="item.sensitive">Sensitive</b></small></span></label>}</div></section>}
    </div>
    @if(destructiveChange()){<label class="adm-impact-confirm full"><input type="checkbox" name="impactConfirmed" [(ngModel)]="impactConfirmed"><span><strong>Confirm access impact</strong>{{roleBase()?.activeAssignedUserCount||0}} active assigned user(s) may lose access. Their permission version will change and they will need to sign in again.</span></label>}@if(duplicateHasSensitiveAccess()){<label class="adm-impact-confirm full"><input type="checkbox" name="duplicateSensitiveConfirmed" [(ngModel)]="duplicateSensitiveConfirmed"><span><strong>Confirm sensitive duplicate</strong>This duplicate includes financial or payroll access. Confirm the new role requires the copied grants.</span></label>}
  </fieldset></form>}
  @if(dialog()==='user'){<form id="access-form" class="adm-form" (ngSubmit)="saveUser()"><fieldset class="adm-form-contents" [disabled]="submitting()"><label class="adm-field">Full name<input name="userName" [(ngModel)]="userForm.name" required maxlength="120"></label><label class="adm-field">Email<input name="userEmail" type="email" [(ngModel)]="userForm.email" required></label><label class="adm-field">Login ID<input name="loginId" [(ngModel)]="userForm.loginId" required maxlength="100"></label><label class="adm-field">Role<select name="userRole" [(ngModel)]="userForm.role" required><option value="" disabled>Select an active role</option>@for(role of userRoleOptions();track role.role){<option [value]="role.role" [disabled]="role.status!=='active'">{{role.name}}{{role.status!=='active'?' — inactive':''}}</option>}</select></label><label class="adm-field">Status<select name="userStatus" [(ngModel)]="userForm.status"><option value="active">Active</option><option value="hidden">Hidden</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select></label><label class="adm-field">{{editingUser()?'New password (optional)':'Temporary password'}}<input name="userPassword" type="password" [(ngModel)]="userForm.password" [required]="!editingUser()" minlength="10" autocomplete="new-password"></label>@if(userError()){<p class="adm-message error full" role="alert">{{userError()}}</p>}@if(currentUserRoleInactive()){<p class="adm-note warning full"><strong>Reassignment required</strong>The current role is inactive. Select an active role before saving.</p>}@if(!editingUser()){<p class="adm-note full"><strong>Administrative account only</strong>This creates a tenant user without staff linkage. To create usable Staff App access, open a staff record and use Login & Role Access.</p>}<fieldset class="adm-branch-fieldset full"><legend class="adm-eyebrow">Branch access</legend><div class="adm-check-list">@for(branch of data()?.branches||[];track branch.id){<label class="adm-check"><input type="checkbox" [checked]="userForm.branchIds.includes(branch.id)" (change)="toggleBranch(branch.id)"><span>{{branch.name}}<small>{{branch.city}}</small></span></label>}</div></fieldset><p class="adm-note full"><strong>Scope is server validated</strong>Only assigned tenant branches can be granted. Access changes invalidate existing sessions.</p></fieldset></form>}
  @if(dialog()==='disable'){<div class="adm-form"><p class="adm-note full"><strong>Disable {{selectedUser()?.name}}?</strong>The user will be signed out after permissionVersion changes. Their tenant record and audit history remain intact.</p></div>}
  <footer><button class="adm-button" type="button" (click)="close()" [disabled]="submitting()">Cancel</button><button class="adm-button" [class.primary]="dialog()!=='disable'" [class.danger]="dialog()==='disable'" [attr.form]="dialog()==='disable'?null:'access-form'" [attr.type]="dialog()==='disable'?'button':'submit'" [disabled]="submitting()" (click)="dialog()==='disable'&&disableUser()">{{submitting()?'Saving…':dialog()==='disable'?'Disable user':dialog()==='role'?'Save access policy':'Save user access'}}</button></footer>
</section>}
`, styleUrls: ["./owner-shell.styles.css", "./owner-administration.css"] })
export class OwnerRolesPermissionsPage implements OnInit {
  @ViewChild("modal") modal?: ElementRef<HTMLElement>;
  @ViewChild("inlineConfirm") inlineConfirm?: ElementRef<HTMLElement>;
  readonly loading=signal(true); readonly error=signal(""); readonly message=signal(""); readonly messageError=signal(false); readonly roleError=signal(""); readonly userError=signal(""); readonly data=signal<OwnerAccessAdministration|null>(null); readonly view=signal<"roles"|"users">("roles"); readonly query=signal(""); readonly scopeBranchId=signal(""); readonly selectedRole=signal<OwnerAdministrationRole|null>(null); readonly selectedUser=signal<OwnerAdministrationUser|null>(null); readonly dialog=signal<AccessDialog>(null); readonly submitting=signal(false); readonly editingRole=signal(false); readonly duplicating=signal(false); readonly editingUser=signal(false); readonly advancedKey=signal(false); readonly templateRole=signal(""); readonly roleBase=signal<OwnerAdministrationRole|null>(null); readonly pendingSensitive=signal<OwnerPermissionItem|null>(null); readonly revokeWarning=signal(false); readonly restoreWarning=signal(false);
  impactConfirmed=false; duplicateSensitiveConfirmed=false; private trigger:HTMLElement|null=null; private loadRequest=0;
  roleForm:OwnerRoleWrite={role:"",name:"",description:"",status:"active",permissionKeys:[],mode:"override"};
  userForm:OwnerUserWrite={name:"",loginId:"",email:"",role:"",branchIds:[],status:"active",password:""};
  readonly roles=computed(()=>{const q=this.query().trim().toLowerCase();return(this.data()?.roles||[]).filter(r=>!q||`${r.name} ${r.role} ${r.description}`.toLowerCase().includes(q));});
  readonly users=computed(()=>{const q=this.query().trim().toLowerCase();return(this.data()?.users||[]).filter(u=>!q||`${u.name} ${u.email} ${u.loginId} ${u.role}`.toLowerCase().includes(q));});
  readonly assignableRoles=computed(()=>(this.data()?.roles||[]).filter(r=>r.status==="active"&&!['owner','superAdmin'].includes(r.role)));
  readonly userRoleOptions=computed(()=>{const active=this.assignableRoles(),current=this.data()?.roles.find(r=>r.role===this.userForm.role);return current&&!active.some(r=>r.role===current.role)?[current,...active]:active;});
  readonly templateRoles=computed(()=>(this.data()?.roles||[]).filter(r=>r.status==="active"));
  readonly allPermissionKeys=computed(()=>[...new Set((this.data()?.permissionGroups||[]).flatMap(g=>g.items.map(i=>i.key)))]);
  readonly allPermissionCount=computed(()=>this.allPermissionKeys().length);
  readonly inheritedCount=computed(()=>this.roleBase()?.inheritedKeys?.length||0);
  readonly allPermissionsGranted=computed(()=>this.allPermissionCount()>0&&this.allPermissionKeys().every(k=>this.roleForm.permissionKeys.includes(k)));
  destructiveChange(){const base=this.roleBase();return this.editingRole()&&!!base&&base.assignedUserCount>0&&((base.status==='active'&&this.roleForm.status==='inactive')||this.effectiveKeys(base).some(key=>!this.roleForm.permissionKeys.includes(key)));}
  duplicateHasSensitiveAccess(){return this.duplicating()&&(this.data()?.permissionGroups||[]).flatMap(group=>group.items).some(item=>item.sensitive&&this.roleForm.permissionKeys.includes(item.key));}
  currentUserRoleInactive(){return !!this.userForm.role&&this.roleStatus(this.userForm.role)!=='active';}

  constructor(readonly api:OwnerAppService,private context:OwnerContextService){} ngOnInit(){void this.load();}
  async load(background=false){const request=++this.loadRequest,scope=this.scopeBranchId();if(!background)this.loading.set(true);this.error.set("");try{const result=await this.api.administrationAccess(scope);if(request!==this.loadRequest||scope!==this.scopeBranchId())return;this.apply(result);if(background)this.show("Access catalogue refreshed.");}catch{if(request===this.loadRequest)this.error.set("Aura could not load the owner access catalogue.");}finally{if(request===this.loadRequest)this.loading.set(false);}}
  async changeScope(branchId:string){this.scopeBranchId.set(branchId);this.selectedRole.set(null);await this.load();}
  private apply(data:OwnerAccessAdministration){this.data.set(data);this.selectedRole.set(data.roles.find(r=>r.role===this.selectedRole()?.role)||data.roles[0]||null);this.selectedUser.set(data.users.find(u=>u.id===this.selectedUser()?.id)||data.users[0]||null);}
  changeQuery(value:string){this.query.set(value);if(this.view()==="roles"&&!this.roles().some(role=>role.role===this.selectedRole()?.role))this.selectedRole.set(null);if(this.view()==="users"&&!this.users().some(user=>user.id===this.selectedUser()?.id))this.selectedUser.set(null);}
  changeView(value:"roles"|"users"){this.view.set(value);this.query.set("");}
  tabKey(event:KeyboardEvent){if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const next=event.key==="Home"?"roles":event.key==="End"?"users":this.view()==="roles"?"users":"roles";this.changeView(next);setTimeout(()=>document.getElementById(`access-tab-${next}`)?.focus());}

  openRole(role:OwnerAdministrationRole|null,duplicate:boolean,event:Event){const capabilities=this.data()?.capabilities;if(!capabilities||(!role&&!capabilities.createRole)||(duplicate&&!capabilities.duplicateRole)||(role&&!duplicate&&!role.editablePolicy))return;this.trigger=event.currentTarget as HTMLElement;this.roleError.set("");this.editingRole.set(!!role&&!duplicate);this.duplicating.set(duplicate);this.advancedKey.set(duplicate);this.templateRole.set(duplicate&&role?role.role:"");this.roleBase.set(role);this.pendingSensitive.set(null);this.revokeWarning.set(false);this.restoreWarning.set(false);this.impactConfirmed=false;this.duplicateSensitiveConfirmed=false;const key=role?(duplicate?this.uniqueRoleKey(`${role.role}Copy`):role.role):"";this.roleForm={role:key,name:role?(duplicate?`${role.name} copy`:role.name):"",description:role?.description||"",status:role?.status||"active",permissionKeys:role?[...this.effectiveKeys(role)]:[],mode:duplicate?"override":role?.policyMode||"override",branchId:this.scopeBranchId(),intent:role&&!duplicate?"update":"create"};this.open("role");}
  roleNameChanged(name:string){this.roleForm={...this.roleForm,name};if(!this.editingRole()&&!this.advancedKey())this.roleForm.role=this.uniqueRoleKey(this.technicalKey(name));}
  applyTemplate(roleKey:string){this.templateRole.set(roleKey);const role=this.data()?.roles.find(r=>r.role===roleKey);this.roleForm={...this.roleForm,permissionKeys:role?[...this.effectiveKeys(role)]:[],mode:"override"};this.roleBase.set(this.editingRole()?this.roleBase():role||null);this.impactConfirmed=false;}
  private technicalKey(name:string){const words=name.trim().replace(/[^A-Za-z0-9]+/g," ").split(/\s+/).filter(Boolean);const value=words.map((word,index)=>index?word.charAt(0).toUpperCase()+word.slice(1):word.charAt(0).toLowerCase()+word.slice(1)).join("").replace(/^[^A-Za-z]+/,"");return (value.length>=3?value:`${value||"role"}Role`).slice(0,41);}
  private uniqueRoleKey(seed:string){const roles=this.data()?.roles||[];let value=seed.slice(0,41),index=2;while(roles.some(r=>r.role.toLowerCase()===value.toLowerCase()&&!(this.editingRole()&&!this.duplicating()&&r.role===this.roleBase()?.role))){const suffix=String(index++);value=`${seed.slice(0,41-suffix.length)}${suffix}`;}return value;}

  requestPermission(item:OwnerPermissionItem){if(item.sensitive&&!this.roleForm.permissionKeys.includes(item.key)){this.pendingSensitive.set(item);this.focusInlineConfirmation();return;}this.togglePermission(item.key);}
  confirmSensitive(){const item=this.pendingSensitive();if(item?.key==="__all__")this.setPermissions(this.allPermissionKeys());else if(item?.key.startsWith("__group:")){const group=this.data()?.permissionGroups.find(value=>value.key===item.key.slice(8));if(group)this.setPermissions([...this.roleForm.permissionKeys,...group.items.map(value=>value.key)]);}else if(item)this.togglePermission(item.key);this.pendingSensitive.set(null);}
  private setPermissions(keys:string[]){this.roleError.set("");this.roleForm={...this.roleForm,permissionKeys:[...new Set(keys)],mode:"override"};this.impactConfirmed=false;}
  togglePermission(key:string){this.setPermissions(this.roleForm.permissionKeys.includes(key)?this.roleForm.permissionKeys.filter(v=>v!==key):[...this.roleForm.permissionKeys,key]);}
  grantAll(){this.revokeWarning.set(false);const sensitive=(this.data()?.permissionGroups||[]).flatMap(group=>group.items).find(item=>item.sensitive&&!this.roleForm.permissionKeys.includes(item.key));if(sensitive){this.pendingSensitive.set({...sensitive,key:"__all__",label:"Grant all permissions"});this.focusInlineConfirmation();return;}this.setPermissions(this.allPermissionKeys());}
  requestRevokeAll(){if(!this.roleForm.permissionKeys.length)return;if(this.editingRole()&&(this.roleBase()?.assignedUserCount||0)>0){this.revokeWarning.set(true);return;}this.confirmRevokeAll();}
  confirmRevokeAll(){this.revokeWarning.set(false);this.setPermissions([]);}
  toggleGroup(groupKey:string){const group=this.data()?.permissionGroups.find(g=>g.key===groupKey);if(!group)return;const keys=group.items.map(i=>i.key),all=keys.every(k=>this.roleForm.permissionKeys.includes(k));if(!all&&group.items.some(item=>item.sensitive&&!this.roleForm.permissionKeys.includes(item.key))){this.pendingSensitive.set({key:`__group:${groupKey}`,label:`Grant all ${group.label} permissions`,resource:"",action:"allow",sensitive:true});this.focusInlineConfirmation();return;}this.setPermissions(all?this.roleForm.permissionKeys.filter(k=>!keys.includes(k)):[...this.roleForm.permissionKeys,...keys]);}
  allInGroupGranted(key:string){const group=this.data()?.permissionGroups.find(g=>g.key===key);return !!group?.items.length&&group.items.every(i=>this.roleForm.permissionKeys.includes(i.key));}
  someInGroupGranted(key:string){const count=this.selectedInGroup(key),total=this.data()?.permissionGroups.find(g=>g.key===key)?.items.length||0;return count>0&&count<total;}
  inheritedState(key:string){const inherited=this.roleBase()?.inheritedKeys?.includes(key);const effective=this.roleForm.permissionKeys.includes(key);return inherited?(effective?"Inherited · effective":"Inherited · revoked by override"):(effective?"Added by override":"Not granted");}

  requestRestoreDefaults(){this.restoreWarning.set(true);this.focusInlineConfirmation();}
  cancelInlineConfirmation(){this.pendingSensitive.set(null);this.restoreWarning.set(false);setTimeout(()=>this.modal?.nativeElement.focus());}
  private focusInlineConfirmation(){setTimeout(()=>this.inlineConfirm?.nativeElement.focus());}
  async restoreDefaults(){const role=this.roleBase();if(!role||this.submitting()||!this.restoreWarning())return;this.restoreWarning.set(false);this.submitting.set(true);this.roleError.set("");try{const result=await this.api.restoreAdministrationRoleDefaults(role.role,this.scopeBranchId());this.apply(result.access);this.selectedRole.set(result.access.roles.find(r=>r.role===role.role)||null);this.close(true);this.show(this.impactMessage("Aura defaults restored.",result.impact.affectedUsers,result.impact.affectedActiveSessions));}catch(error){this.roleError.set(this.errorText(error,"Aura defaults could not be restored."));}finally{this.submitting.set(false);}}
  async saveRole(){if(this.submitting())return;const key=this.roleForm.role.trim(),name=this.roleForm.name.trim();if(!name){this.roleError.set("Add a display name.");return;}if(!/^[A-Za-z][A-Za-z0-9_-]{2,40}$/.test(key)){this.roleError.set("Technical key must start with a letter and use 3–41 letters, numbers, underscores or hyphens.");return;}if((this.data()?.roles||[]).some(r=>r.role.toLowerCase()===key.toLowerCase()&&(!this.editingRole()||r.role!==this.roleBase()?.role))){this.roleError.set("That technical key already exists. Choose a unique key.");return;}if(this.destructiveChange()&&!this.impactConfirmed){this.roleError.set("Confirm the assigned-user impact before saving this access reduction.");return;}if(this.duplicateHasSensitiveAccess()&&!this.duplicateSensitiveConfirmed){this.roleError.set("Confirm the duplicated sensitive access before saving this role.");return;}this.submitting.set(true);this.roleError.set("");try{const result=await this.api.saveAdministrationRole({...this.roleForm,role:key,name,branchId:this.scopeBranchId(),intent:this.editingRole()?"update":"create"});this.apply(result.access);this.selectedRole.set(result.access.roles.find(r=>r.role===key)||null);this.close(true);this.show(this.impactMessage("Access policy saved.",result.impact.affectedUsers,result.impact.affectedActiveSessions));}catch(error){this.roleError.set(this.errorText(error,"The role was not saved. Review the key, status and permission selection."));}finally{this.submitting.set(false);}}

  openUser(user:OwnerAdministrationUser|null,event:Event){if(user&&this.isCurrentOwner(user))return;this.trigger=event.currentTarget as HTMLElement;this.editingUser.set(!!user);this.userError.set("");if(user)this.selectedUser.set(user);const defaultRole=this.assignableRoles()[0]?.role||"";this.userForm=user?{name:user.name,loginId:user.loginId,email:user.email,role:user.role,branchIds:[...user.branchIds],status:user.status,password:""}:{name:"",loginId:"",email:"",role:defaultRole,branchIds:[],status:"active",password:""};this.open("user");}
  toggleBranch(id:string){this.userForm={...this.userForm,branchIds:this.userForm.branchIds.includes(id)?this.userForm.branchIds.filter(v=>v!==id):[...this.userForm.branchIds,id]};}
  async saveUser(){if(this.submitting())return;if(!this.userForm.name.trim()||!this.userForm.email.trim()||!this.userForm.loginId.trim()){this.userError.set("Name, email and login ID are required.");return;}if(this.currentUserRoleInactive()){this.userError.set("Select an active role before saving this account.");return;}if(!this.userForm.branchIds.length){this.userError.set("Select at least one assigned branch.");return;}if(!this.editingUser()&&String(this.userForm.password||"").length<10){this.userError.set("Temporary password must contain at least 10 characters.");return;}this.submitting.set(true);this.userError.set("");try{const payload={...this.userForm,...(!this.userForm.password?{password:undefined}:{})};const result=this.editingUser()?await this.api.updateAdministrationUser(this.selectedUser()!.id,payload):await this.api.createAdministrationUser(payload);this.apply(result.access);this.selectedUser.set(result.user);this.close(true);this.show("User access saved. Changed sessions must authenticate again.");}catch(error){this.userError.set(this.errorText(error,"The user change was not saved. Review role, login, branch scope and owner protections."));}finally{this.submitting.set(false);}}
  openDisable(user:OwnerAdministrationUser,event:Event){this.trigger=event.currentTarget as HTMLElement;this.selectedUser.set(user);this.open("disable");}
  async disableUser(){const user=this.selectedUser();if(!user||this.submitting()||this.isCurrentOwner(user))return;this.submitting.set(true);try{const result=await this.api.updateAdministrationUser(user.id,{status:"disabled"});this.apply(result.access);this.selectedUser.set(result.user);this.close(true);this.show("User disabled. Their record and audit history were retained.");}catch(error){this.show(this.errorText(error,"The user could not be disabled. Check last-owner protections."),true);}finally{this.submitting.set(false);}}

  effectiveKeys(role:OwnerAdministrationRole){return Array.isArray(role.effectiveKeys)?role.effectiveKeys:role.permissionKeys||[];}
  effectiveCount(role:OwnerAdministrationRole){return this.effectiveKeys(role).filter(k=>this.allPermissionKeys().includes(k)).length;}
  visibleGroups(role:OwnerAdministrationRole){return(this.data()?.permissionGroups||[]).filter(g=>g.items.some(i=>this.effectiveKeys(role).includes(i.key)));}
  grantsInGroup(role:OwnerAdministrationRole,key:string){return this.data()?.permissionGroups.find(g=>g.key===key)?.items.filter(i=>this.effectiveKeys(role).includes(i.key)).length||0;}
  selectedInGroup(key:string){return this.data()?.permissionGroups.find(g=>g.key===key)?.items.filter(i=>this.roleForm.permissionKeys.includes(i.key)).length||0;}
  sourceLabel(role:OwnerAdministrationRole){return role.policySource==='branch-override'?'Branch override':role.policySource==='tenant-override'?'Tenant override':'Aura default';}
  roleName(key:string){return this.data()?.roles.find(r=>r.role===key)?.name||key;} roleStatus(key:string){return this.data()?.roles.find(r=>r.role===key)?.status||"inactive";}
  branchName(id:string){return this.data()?.branches.find(b=>b.id===id)?.name||id;} branchNames(ids:string[]){return ids.length?ids.map(id=>this.branchName(id)).join(", "):"No branch access";}
  isCurrentOwner(user:OwnerAdministrationUser){return user.id===this.api.user()?.id;} date(value:string){return this.context.formatDateTime(value);}
  dialogTitle(){return this.dialog()==="role"?(this.duplicating()?"Duplicate role":this.editingRole()?(this.roleBase()?.kind==='system'?"Customize App Access":"Edit role"):"Create role"):this.dialog()==="user"?(this.editingUser()?"Edit user access":"Create administrative user"):"Confirm disable";}
  private impactMessage(prefix:string,users:number,sessions:number){return users?`${prefix} ${users} assigned user${users===1?"":"s"} affected${sessions?`; ${sessions} active session${sessions===1?"":"s"} must sign in again`:""}.`:prefix;}
  private errorText(error:unknown,fallback:string){if(error&&typeof error==="object"){const body="error" in error?(error as {error?:unknown}).error:undefined;if(body&&typeof body==="object"){const nested="error" in body?(body as {error?:unknown}).error:undefined;if(typeof nested==="string")return nested;if(nested&&typeof nested==="object"&&"message" in nested&&typeof nested.message==="string")return nested.message;if("message" in body&&typeof body.message==="string")return body.message;}}return error instanceof Error&&error.message?error.message:fallback;}
  private show(value:string,error=false){this.message.set(value);this.messageError.set(error);}
  private open(value:Exclude<AccessDialog,null>){this.dialog.set(value);document.documentElement.classList.add("staff-overlay-open");setTimeout(()=>this.modal?.nativeElement.focus());}
  close(force=false){if(this.submitting()&&!force)return;this.dialog.set(null);this.pendingSensitive.set(null);this.restoreWarning.set(false);document.documentElement.classList.remove("staff-overlay-open");setTimeout(()=>this.trigger?.focus());}
  @HostListener("window:keydown",["$event"]) key(event:KeyboardEvent){if(!this.dialog())return;if(event.key==="Escape"&&!this.submitting()){event.preventDefault();this.close();return;}if(event.key!=="Tab")return;const panel=this.modal?.nativeElement,nodes=panel?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!panel||!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(!panel.contains(document.activeElement)){event.preventDefault();(event.shiftKey?last:first).focus();}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
}
