import { CommonModule } from "@angular/common";
import { Component, effect, signal, untracked } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { PaiseInrPipe } from "../../core/paise-inr.pipe";
import { OwnerAppService, OwnerPurchaseOrder } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";

@Component({standalone:true,imports:[CommonModule,FormsModule,PaiseInrPipe],template:`
<article class="ops-page" [attr.aria-busy]="loading()"><header class="ops-header"><div><p class="ops-eyebrow">Supplier desk</p><h1>Purchase Orders</h1><p>Create supplier purchase orders and track draft, sent, received and cancelled states.</p></div><button class="ops-button" (click)="load()" [disabled]="loading()">{{loading()?'Refreshing...':'Refresh'}}</button></header>@if(error()){<p class="ops-notice error">{{error()}}</p>}
<section class="po-layout"><form class="ops-panel po-form" (ngSubmit)="create()"><header class="ops-panel-head"><h2>New PO</h2></header><label class="ops-field"><span>Branch</span><select name="branchId" [(ngModel)]="form.branchId"><option value="">Choose branch</option>@for(branch of context.branches();track branch.id){<option [value]="branch.id">{{branch.name}}</option>}</select></label><label class="ops-field"><span>Supplier</span><input name="supplier" required [(ngModel)]="form.supplierName"></label><label class="ops-field"><span>Supplier phone</span><input name="supplierPhone" [(ngModel)]="form.supplierPhone"></label><label class="ops-field"><span>Expected</span><input type="date" name="expected" [(ngModel)]="form.expectedAt"></label><label class="ops-field"><span>Item</span><input name="item" required [(ngModel)]="line.itemName"></label><label class="ops-field"><span>SKU</span><input name="sku" [(ngModel)]="line.sku"></label><label class="ops-field"><span>Qty</span><input type="number" min="1" name="qty" [(ngModel)]="line.quantity"></label><label class="ops-field"><span>Unit cost</span><input type="number" min="0" step="1" name="unit" [ngModel]="line.unitCostPaise/100" (ngModelChange)="line.unitCostPaise=paise($event)"></label><label class="ops-field"><span>Tax</span><input type="number" min="0" step="1" name="tax" [ngModel]="form.taxPaise/100" (ngModelChange)="form.taxPaise=paise($event)"></label><label class="ops-field wide"><span>Notes</span><textarea name="notes" [(ngModel)]="form.notes"></textarea></label><button class="ops-button primary" [disabled]="saving()||!form.branchId">Create purchase order</button></form>
<section class="ops-panel"><header class="ops-panel-head"><h2>Open orders</h2><select [ngModel]="status()" (ngModelChange)="status.set($event);load()"><option value="all">All</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="received">Received</option><option value="cancelled">Cancelled</option></select></header><div class="ops-cards always">@for(po of orders();track po.id){<article class="ops-card static"><div><h3>{{po.poNumber}}</h3><span class="ops-status">{{po.status}}</span></div><p>{{po.supplierName}} · {{po.lines.length}} line(s)</p><small>{{po.totalPaise|paiseInr}} · {{po.expectedAt?date(po.expectedAt):'No ETA'}}</small><div class="po-actions"><button class="ops-button" (click)="setStatus(po,'sent')">Sent</button><button class="ops-button" (click)="setStatus(po,'received')">Received</button><button class="ops-button" (click)="setStatus(po,'cancelled')">Cancel</button></div></article>}@empty{<p class="ops-state">No purchase orders for this scope.</p>}</div></section></section></article>
`,styleUrls:["./owner-shell.styles.css","./owner-operations.css"],styles:[`.po-layout{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,1.2fr);gap:14px}.po-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.wide{grid-column:1/-1}.ops-cards.always{display:grid;gap:10px}.ops-card.static{text-align:left}.po-actions{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:760px){.po-layout,.po-form{grid-template-columns:1fr}}`]} )
export class OwnerPurchaseOrdersPage{readonly loading=signal(false);readonly saving=signal(false);readonly error=signal("");readonly orders=signal<OwnerPurchaseOrder[]>([]);readonly status=signal("all");form={branchId:"",supplierName:"",supplierPhone:"",expectedAt:"",taxPaise:0,notes:""};line={itemName:"",sku:"",quantity:1,unitCostPaise:0};constructor(private api:OwnerAppService,readonly context:OwnerContextService){effect(()=>{const branch=context.selectedBranchId();untracked(()=>{this.form.branchId=branch||this.context.branches()[0]?.id||"";void this.load();});});}async load(){this.loading.set(true);this.error.set("");try{const r=await this.api.ownerPurchaseOrders({branchId:this.context.selectedBranchId()||"all",status:this.status()});this.orders.set(r.items);}catch{this.error.set("Purchase orders could not be loaded.");}finally{this.loading.set(false);}}async create(){if(!this.form.branchId||!this.form.supplierName.trim()||!this.line.itemName.trim())return;this.saving.set(true);try{await this.api.createOwnerPurchaseOrder({...this.form,expectedAt:this.form.expectedAt?`${this.form.expectedAt}T00:00:00.000Z`:undefined,lines:[this.line]});this.form={branchId:this.form.branchId,supplierName:"",supplierPhone:"",expectedAt:"",taxPaise:0,notes:""};this.line={itemName:"",sku:"",quantity:1,unitCostPaise:0};await this.load();}catch{this.error.set("Purchase order could not be created.");}finally{this.saving.set(false);}}async setStatus(po:OwnerPurchaseOrder,status:string){await this.api.setOwnerPurchaseOrderStatus(po.id,status);await this.load();}paise(v:string|number){return Math.round((Number(v)||0)*100);}date(v:string){return this.context.formatDate(v);}}
