import { CommonModule } from "@angular/common";
import { Component, ElementRef, HostListener, OnInit, ViewChild, computed, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerBranchAdministration, OwnerBranchCatalogue, OwnerBranchWrite } from "./owner-administration.models";

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
  <article class="adm-page" [attr.aria-busy]="loading()" [attr.inert]="dialog() ? '' : null">
    <header class="adm-hero"><div><p class="adm-eyebrow">Administration · Branches</p><h1>Your locations, clearly governed.</h1><p>Maintain the confirmed branch record while specialist configuration stays with its authoritative Aura module.</p></div><div class="adm-actions">@if(!error()||catalogue()){<button class="adm-button" type="button" [disabled]="loading()" (click)="load(true)">↻ Refresh</button>}@if(catalogue()?.capabilities?.create){<button class="adm-button primary" type="button" (click)="openCreate($event)">＋ Add branch</button>}</div></header>
    @if(message()){<p class="adm-message" [class.error]="messageError()" [attr.role]="messageError()?'alert':'status'">{{message()}}</p>}
    <section class="adm-toolbar" aria-label="Branch filters"><label class="adm-field grow" for="branch-search">Search branches<input id="branch-search" type="search" [ngModel]="query()" (ngModelChange)="query.set($event)" placeholder="Name, city, address or phone"></label><label class="adm-field" for="branch-status">Status<select id="branch-status" [ngModel]="status()" (ngModelChange)="status.set($event)"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></section>
    @if(loading()&&!catalogue()){<div class="adm-skeleton" aria-label="Loading branches"><i></i><i></i><i></i></div>}@else if(error()&&!catalogue()){<section class="adm-state" role="alert"><span>!</span><h2>Branches unavailable</h2><p>{{error()}}</p><button class="adm-button" (click)="load()">Try again</button></section>}@else{
      <section class="adm-layout"><section class="adm-panel"><header class="adm-panel-head"><h2>Branch directory</h2><span>{{filtered().length}} shown</span></header><div class="adm-list">
        @for(branch of filtered();track branch.id){<button type="button" [class.selected]="selected()?.id===branch.id" (click)="selected.set(branch)"><span class="adm-avatar">{{branch.name.charAt(0)}}</span><span><strong>{{branch.name}}</strong><small>{{branch.city}} · {{branch.address||'Address not recorded'}}</small></span><span class="adm-status" [attr.data-active]="branch.status==='active'">{{branch.status}}</span></button>}
        @empty{<div class="adm-state"><span>—</span><h2>{{items().length?'No matching branches':'No assigned branches'}}</h2><p>{{items().length?'Adjust search or status filters.':'Create a branch to begin; the creator is assigned securely.'}}</p></div>}
      </div></section>
      <section class="adm-panel">@if(selected();as branch){<div class="adm-detail"><div class="adm-detail-hero"><div><p class="adm-eyebrow">Branch record</p><h2>{{branch.name}}</h2><p>{{branch.city}} · {{branch.timezone||'Asia/Kolkata'}}</p></div><div class="adm-actions">@if(catalogue()?.capabilities?.update){<button class="adm-button" (click)="openEdit(branch,$event)">Edit</button>}@if(catalogue()?.capabilities?.deactivate){<button class="adm-button" [class.danger]="branch.status==='active'" (click)="confirmStatus(branch,$event)">{{branch.status==='active'?'Deactivate':'Activate'}}</button>}</div></div><dl class="adm-facts"><div><dt>Address</dt><dd>{{branch.address||'Not recorded'}}</dd></div><div><dt>Contact</dt><dd>{{branch.phone||'Not recorded'}}</dd></div><div><dt>GSTIN</dt><dd>{{branch.gstin||'Not recorded'}}</dd></div><div><dt>Online booking</dt><dd>{{branch.onlineBookingEnabled===undefined?'Contract unavailable':branch.onlineBookingEnabled?'Enabled':'Disabled'}}</dd></div><div><dt>Peak reserve</dt><dd>{{branch.peakSlotsReservedPct===undefined?'Contract unavailable':branch.peakSlotsReservedPct+'%'}}</dd></div><div><dt>Public slug</dt><dd>{{branch.slug||'Not recorded'}}</dd></div></dl><p class="adm-note"><strong>Deactivation is reversible.</strong>Aura changes status only. No branch record or connected history is deleted.</p><div class="adm-capabilities">@for(note of availability();track note.key){<div><strong>{{label(note.key)}}</strong><p>{{note.value}}</p></div>}</div></div>}@else{<div class="adm-state"><span>↗</span><h2>Select a branch</h2><p>Choose a location to review its confirmed operational fields and availability notes.</p></div>}</section></section>
    }
  </article>
  @if(dialog()){<button class="adm-backdrop" type="button" (click)="closeDialog()" aria-label="Close dialog"></button><section class="adm-dialog" role="dialog" aria-modal="true" [attr.aria-labelledby]="dialog()==='status'?'branch-status-title':'branch-form-title'" #modal tabindex="-1">
    <header><div><p class="adm-eyebrow">Branch administration</p><h2 [id]="dialog()==='status'?'branch-status-title':'branch-form-title'">{{dialog()==='create'?'Add branch':dialog()==='edit'?'Edit branch':'Confirm status change'}}</h2></div><button class="adm-close" type="button" (click)="closeDialog()" aria-label="Close">×</button></header>
    @if(dialog()==='status'){<div class="adm-form"><p class="adm-note full"><strong>{{selected()?.status==='active'?'Deactivate':'Activate'}} {{selected()?.name}}?</strong>{{selected()?.status==='active'?'This branch will remain in Aura with its history intact. Operational visibility may change immediately.':'This branch will return to active status.'}}</p></div>}@else{
      <form id="branch-form" class="adm-form" (ngSubmit)="saveBranch()"><label class="adm-field">Branch name<input name="name" [(ngModel)]="form.name" required maxlength="120" [attr.aria-invalid]="submitted()&&!form.name.trim()"><span class="adm-error" *ngIf="submitted()&&!form.name.trim()">Branch name is required.</span></label><label class="adm-field">City<input name="city" [(ngModel)]="form.city" required maxlength="120" [attr.aria-invalid]="submitted()&&!form.city.trim()"><span class="adm-error" *ngIf="submitted()&&!form.city.trim()">City is required.</span></label><label class="adm-field full">Address<input name="address" [(ngModel)]="form.address" maxlength="300"></label><label class="adm-field">Phone<input name="phone" [(ngModel)]="form.phone" inputmode="tel" maxlength="40"></label><label class="adm-field">GSTIN<input name="gstin" [(ngModel)]="form.gstin" maxlength="30"></label><label class="adm-field">Timezone<input name="timezone" [(ngModel)]="form.timezone" placeholder="Asia/Kolkata"></label><label class="adm-field">Public slug<input name="slug" [(ngModel)]="form.slug" maxlength="100"></label><label class="adm-field">Peak slots reserved %<input name="peakSlotsReservedPct" type="number" [(ngModel)]="form.peakSlotsReservedPct" min="0" max="100"></label><label class="adm-switch full">Online booking<input name="onlineBookingEnabled" type="checkbox" [(ngModel)]="form.onlineBookingEnabled"></label></form>
    }<footer><button class="adm-button" type="button" (click)="closeDialog()">Cancel</button><button class="adm-button" [class.primary]="dialog()!=='status'" [class.danger]="dialog()==='status'&&selected()?.status==='active'" [attr.form]="dialog()==='status'?null:'branch-form'" [attr.type]="dialog()==='status'?'button':'submit'" [disabled]="submitting()" (click)="dialog()==='status'&&saveStatus()">{{submitting()?'Saving…':dialog()==='status'?'Confirm change':'Save branch'}}</button></footer>
  </section>}
  `,
  styleUrls: ["./owner-shell.styles.css", "./owner-administration.css"]
})
export class OwnerBranchesPage implements OnInit {
  @ViewChild("modal") modal?: ElementRef<HTMLElement>;
  readonly loading=signal(true);readonly error=signal("");readonly message=signal("");readonly messageError=signal(false);readonly catalogue=signal<OwnerBranchCatalogue|null>(null);readonly selected=signal<OwnerBranchAdministration|null>(null);readonly query=signal("");readonly status=signal("");readonly dialog=signal<"create"|"edit"|"status"|null>(null);readonly submitting=signal(false);readonly submitted=signal(false);
  form:OwnerBranchWrite=this.emptyForm();private trigger:HTMLElement|null=null;
  readonly items=computed(()=>this.catalogue()?.items||[]);readonly filtered=computed(()=>{const q=this.query().trim().toLowerCase();return this.items().filter(b=>(!this.status()||b.status===this.status())&&(!q||`${b.name} ${b.city} ${b.address||""} ${b.phone||""}`.toLowerCase().includes(q)));});readonly availability=computed(()=>Object.entries(this.catalogue()?.availability||{}).map(([key,value])=>({key,value})));
  constructor(private readonly api:OwnerAppService,private readonly context:OwnerContextService){}
  ngOnInit(){void this.load();}
  async load(background=false){if(!background)this.loading.set(true);this.error.set("");try{const data=await this.api.administrationBranches();this.catalogue.set(data);const current=this.selected();this.selected.set(data.items.find(b=>b.id===current?.id)||data.items[0]||null);if(background)this.message.set("Branch directory refreshed.");}catch{this.error.set("Aura could not load your assigned branch directory.");}finally{this.loading.set(false);}}
  openCreate(event:Event){this.trigger=event.currentTarget as HTMLElement;this.form=this.emptyForm();this.submitted.set(false);this.open("create");}
  openEdit(branch:OwnerBranchAdministration,event:Event){this.trigger=event.currentTarget as HTMLElement;this.selected.set(branch);this.form={name:branch.name,city:branch.city,address:branch.address||"",phone:branch.phone||"",gstin:branch.gstin||"",timezone:branch.timezone||"Asia/Kolkata",onlineBookingEnabled:Boolean(branch.onlineBookingEnabled),peakSlotsReservedPct:branch.peakSlotsReservedPct,peakHoursDefinition:branch.peakHoursDefinition||"",slug:branch.slug||""};this.submitted.set(false);this.open("edit");}
  confirmStatus(branch:OwnerBranchAdministration,event:Event){this.trigger=event.currentTarget as HTMLElement;this.selected.set(branch);this.open("status");}
  private open(kind:"create"|"edit"|"status"){this.dialog.set(kind);document.documentElement.classList.add("staff-overlay-open");setTimeout(()=>this.modal?.nativeElement.focus());}
  closeDialog(){this.dialog.set(null);document.documentElement.classList.remove("staff-overlay-open");setTimeout(()=>this.trigger?.focus());}
  async saveBranch(){this.submitted.set(true);if(!this.form.name.trim()||!this.form.city.trim()||this.submitting())return;this.submitting.set(true);this.message.set("");try{const result=this.dialog()==="create"?await this.api.createAdministrationBranch(this.form):await this.api.updateAdministrationBranch(this.selected()!.id,this.form);this.closeDialog();await this.load();this.selected.set(this.items().find(b=>b.id===result.branch.id)||result.branch);await this.context.loadBranches();this.messageError.set(false);this.message.set(result.requiresReauthentication?"Branch created and assigned. Your access was refreshed to protect the new scope.":"Branch details saved.");}catch{this.messageError.set(true);this.message.set("The branch change was not saved. Review the fields and try again.");}finally{this.submitting.set(false);}}
  async saveStatus(){const branch=this.selected();if(!branch||this.submitting())return;this.submitting.set(true);try{const result=await this.api.setAdministrationBranchStatus(branch.id,branch.status==="active"?"inactive":"active");this.closeDialog();await this.load();this.selected.set(this.items().find(b=>b.id===result.branch.id)||result.branch);await this.context.loadBranches();this.messageError.set(false);this.message.set(`Branch ${result.branch.status}. No records were deleted.`);}catch{this.messageError.set(true);this.message.set("The status change was not saved. Refresh and try again.");}finally{this.submitting.set(false);}}
  label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
  private emptyForm():OwnerBranchWrite{return{name:"",city:"",address:"",phone:"",gstin:"",timezone:"Asia/Kolkata",onlineBookingEnabled:true,peakSlotsReservedPct:0,peakHoursDefinition:"",slug:""};}
  @HostListener("window:keydown",["$event"]) key(event:KeyboardEvent){if(!this.dialog())return;if(event.key==="Escape"){event.preventDefault();this.closeDialog();return;}if(event.key!=="Tab")return;const nodes=this.modal?.nativeElement.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
}
