import { CommonModule } from "@angular/common";
import { Component, effect, signal, untracked } from "@angular/core";
import { PaiseInrPipe } from "../../core/paise-inr.pipe";
import { OwnerAppService, OwnerBusyHourCell } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";

const DAYS = ["", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const HOURS = Array.from({length:14},(_,i)=>i+8);

@Component({standalone:true,imports:[CommonModule,PaiseInrPipe],template:`
<article class="ops-page" [attr.aria-busy]="loading()"><header class="ops-header"><div><p class="ops-eyebrow">Demand map</p><h1>Busy Hours</h1><p>See appointment demand by weekday and hour for the selected period and branch.</p></div><button class="ops-button" (click)="load()" [disabled]="loading()">{{loading()?'Refreshing...':'Refresh'}}</button></header>@if(error()){<p class="ops-notice error">{{error()}}</p>}
<section class="ops-panel"><header class="ops-panel-head"><h2>Week heatmap</h2><span>{{totalAppointments()}} appointments</span></header><div class="heatmap" role="table" aria-label="Busy hour heatmap"><div></div>@for(hour of hours;track hour){<b>{{hour}}:00</b>}@for(day of dayNumbers;track day){<strong>{{days[day]}}</strong>@for(hour of hours;track hour){@if(cell(day,hour);as c){<article [style.--hot.%]="c.intensity" [title]="days[day]+' '+hour+':00 · '+c.appointments+' appointments'"><span>{{c.appointments}}</span><small>{{c.valuePaise|paiseInr}}</small></article>}@else{<article class="empty"><span>0</span></article>}}}</div></section></article>
`,styleUrls:["./owner-shell.styles.css","./owner-operations.css"],styles:[`.heatmap{display:grid;grid-template-columns:52px repeat(14,minmax(54px,1fr));gap:6px;overflow:auto}.heatmap>b,.heatmap>strong{font-size:.62rem;color:var(--owner-muted);align-self:center}.heatmap article{min-height:54px;border:1px solid var(--owner-line);border-radius:12px;padding:7px;background:color-mix(in srgb,var(--owner-accent) var(--hot),var(--owner-panel));display:grid;gap:2px}.heatmap article.empty{--hot:0%;opacity:.55}.heatmap span{font-weight:850}.heatmap small{font-size:.52rem;color:var(--owner-muted)}@media(max-width:760px){.heatmap{grid-template-columns:46px repeat(14,58px)}}`]} )
export class OwnerBusyHoursPage{readonly loading=signal(false);readonly error=signal("");readonly cells=signal<OwnerBusyHourCell[]>([]);readonly hours=HOURS;readonly days=DAYS;readonly dayNumbers=[1,2,3,4,5,6,7];constructor(private api:OwnerAppService,readonly context:OwnerContextService){effect(()=>{const b=context.selectedBranchId();const r=context.periodRange();untracked(()=>{void b;void r;void this.load();});});}async load(){const r=this.context.periodRange();this.loading.set(true);this.error.set("");try{const data=await this.api.ownerBusyHours({branchId:this.context.selectedBranchId()||"all",fromDate:r.start,toDate:r.end});this.cells.set(data.cells);}catch{this.error.set("Busy-hour heatmap could not be loaded.");}finally{this.loading.set(false);}}cell(dayOfWeek:number,hour:number){return this.cells().find(c=>c.dayOfWeek===dayOfWeek&&c.hour===hour)||null;}totalAppointments(){return this.cells().reduce((s,c)=>s+c.appointments,0);}}
