import { Component, ElementRef, HostListener, OnDestroy, ViewChild, computed, effect, signal, untracked } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { ActivatedRoute } from "@angular/router";
import { PaiseInrPipe } from "../../core/paise-inr.pipe";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerClient, OwnerClientDetail, OwnerOperationsMetadata, OwnerOperationsPage } from "./owner-operations.models";

@Component({ standalone: true, imports: [FormsModule, PaiseInrPipe], template: `
<article class="ops-page" [attr.aria-busy]="loading()">
  <header class="ops-header"><div><p class="ops-eyebrow">Client relationships</p><h1>Clients</h1><p>Search authoritative client records, visit history and financial relationship across your assigned branches.</p></div>@if (!blockingError()) { <div class="ops-actions"><button class="ops-button" type="button" [disabled]="loading()" (click)="load()">{{ loading() ? 'Refreshing…' : 'Refresh' }}</button></div> }</header>
  @if (metadata()?.partial) { <p class="ops-notice" role="status">Some profile sources are unavailable. Saved client, appointment, purchase and membership data remains visible.</p> }
  @if (refreshError()) { <p class="ops-notice error" role="alert">{{ refreshError() }}</p> }
  <section class="ops-toolbar" aria-label="Client filters">
    <label class="ops-field ops-search"><span>Search clients</span><input type="search" [ngModel]="search()" (ngModelChange)="searchChanged($event)" placeholder="Name, phone, email or client ID" autocomplete="off" />@if(search()){<button type="button" (click)="clearSearch()" aria-label="Clear client search">×</button>}</label>
    <label class="ops-field"><span>Relationship</span><select [ngModel]="relationship()" (ngModelChange)="relationship.set($event); filtersChanged()"><option value="">All clients</option><option value="new">New</option><option value="returning">Returning</option></select></label>
    <label class="ops-field"><span>Status</span><select [ngModel]="status()" (ngModelChange)="status.set($event); filtersChanged()"><option value="">Any status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
    <label class="ops-field"><span>Balance</span><select [ngModel]="outstanding()" (ngModelChange)="outstanding.set($event); filtersChanged()"><option value="">Any balance</option><option value="yes">Outstanding only</option></select></label>
    <label class="ops-field"><span>Last visit</span><select [ngModel]="lastVisit()" (ngModelChange)="lastVisit.set($event); filtersChanged()"><option value="">Any time</option><option value="range">Current period</option><option value="never">Never visited</option></select></label>
  </section>
  <section class="ops-panel" aria-labelledby="client-results-title">
    <header class="ops-panel-head"><h2 id="client-results-title">Client directory</h2><span>{{ page()?.total || 0 }} clients</span></header>
    @if (loading() && !items().length) { <div class="ops-skeleton" aria-label="Loading clients"><i></i><i></i><i></i><i></i></div> }
    @else if (blockingError()) { <div class="ops-state" role="alert"><span>!</span><h2>Clients unavailable</h2><p>{{ blockingError() }}</p><button class="ops-button" type="button" (click)="load()">Try again</button></div> }
    @else if (!items().length) { <div class="ops-state"><span>—</span><h2>No matching clients</h2><p>Clear or change the current filters to broaden the directory.</p><button class="ops-button" type="button" (click)="resetFilters()">Clear filters</button></div> }
    @else {
      <table class="ops-table"><thead><tr><th style="width:26%">Client</th><th>Branch</th><th>Relationship</th><th>Spend</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>@for(client of items();track client.id){<tr tabindex="0" (click)="open(client,$event)" (keydown.enter)="open(client,$event)" [class.selected]="detail()?.client?.id===client.id"><td><strong>{{ client.name }}</strong><small>{{ maskedContact(client) }}</small></td><td><strong>{{ client.branchName }}</strong><small>{{ client.id }}</small></td><td><strong>{{ client.visitCount }} visits</strong><small>{{ client.lastVisitAt ? date(client.lastVisitAt) : 'No recorded visit' }}</small></td><td><strong>{{ client.totalSpendPaise | paiseInr }}</strong><small>Recorded total</small></td><td><strong>{{ client.outstandingPaise | paiseInr }}</strong><small>Open invoices</small></td><td><span class="ops-status" [attr.data-tone]="client.status==='active'?'success':'neutral'">{{ client.status }}</span></td></tr>}</tbody></table>
      <div class="ops-cards">@for(client of items();track client.id){<button class="ops-card" type="button" (click)="open(client,$event)"><div><h3>{{ client.name }}</h3><span class="ops-status">{{ client.status }}</span></div><p>{{ maskedContact(client) }} · {{ client.branchName }}</p><small>{{ client.visitCount }} visits · {{ client.totalSpendPaise | paiseInr }} spend</small></button>}</div>
      <footer class="ops-pagination"><span>Page {{ page()?.page }} of {{ page()?.totalPages }}</span><button type="button" [disabled]="page()?.page===1||loading()" (click)="go(-1)" aria-label="Previous page">←</button><button type="button" [disabled]="!page()?.hasMore||loading()" (click)="go(1)" aria-label="Next page">→</button></footer>
    }
  </section>
</article>
@if (selected()) { <button class="ops-backdrop" type="button" (click)="close()" aria-label="Close client profile"></button><aside class="ops-drawer" role="dialog" aria-modal="true" aria-labelledby="client-detail-title" #drawer tabindex="-1"><header><div><p class="ops-eyebrow">Client profile</p><h2 id="client-detail-title">{{ selected()?.name }}</h2></div><button class="ops-close" type="button" (click)="close()" aria-label="Close profile">×</button></header><div class="ops-drawer-body">
  @if(detailLoading()){<div class="ops-skeleton"><i></i><i></i></div>}@else if(detailError()){<div class="ops-state"><span>!</span><h2>Profile unavailable</h2><p>{{detailError()}}</p></div>}@else if(detail();as data){
    <section class="ops-detail-hero"><strong>{{data.client.name}}</strong><p>{{maskedContact(data.client)}} · {{data.client.branchName}}</p></section>
    <section class="ops-detail-section"><h3>Relationship</h3><dl class="ops-detail-grid"><div><dt>Total spend</dt><dd>{{data.client.totalSpendPaise|paiseInr}}</dd></div><div><dt>Outstanding</dt><dd>{{data.client.outstandingPaise|paiseInr}}</dd></div><div><dt>Wallet</dt><dd>{{data.client.walletBalancePaise|paiseInr}}</dd></div><div><dt>Rewards</dt><dd>{{data.client.loyaltyPoints}} points</dd></div><div><dt>Visits</dt><dd>{{data.client.visitCount}}</dd></div><div><dt>Last visit</dt><dd>{{data.client.lastVisitAt?date(data.client.lastVisitAt):'Not recorded'}}</dd></div><div><dt>Membership</dt><dd>{{data.membership?.planName||'None recorded'}}</dd></div></dl></section>
    @if(data.client.notes){<section class="ops-detail-section"><h3>Notes</h3><p>{{data.client.notes}}</p></section>}
    <section class="ops-detail-section"><h3>Appointments</h3><div class="ops-timeline">@for(item of data.appointments;track item.id){<article><strong>{{dateTime(item.startAt)}} · {{item.status}}</strong><p>{{item.branchName}}{{item.notes?' · '+item.notes:''}}</p></article>}@empty{<p>No saved appointments in the accessible branch scope.</p>}</div></section>
    <section class="ops-detail-section"><h3>Purchases</h3><div class="ops-timeline">@for(item of data.purchases;track item.id){<article><strong>{{item.invoiceNumber||'Sale'}} · {{item.totalPaise|paiseInr}}</strong><p>{{item.branchName}} · {{item.status}} · Balance {{item.balancePaise|paiseInr}}</p><small>{{dateTime(item.createdAt)}}</small></article>}@empty{<p>No saved purchases in the accessible branch scope.</p>}</div></section>
  }
</div></aside>}
`, styleUrls: ["./owner-shell.styles.css", "./owner-operations.css"] })
export class OwnerClientsPage implements OnDestroy {
  @ViewChild("drawer") drawer?: ElementRef<HTMLElement>;
  readonly items=signal<OwnerClient[]>([]);readonly page=signal<OwnerOperationsPage|null>(null);readonly metadata=signal<OwnerOperationsMetadata|null>(null);readonly loading=signal(true);readonly blockingError=signal("");readonly refreshError=signal("");readonly search=signal("");readonly debouncedSearch=signal("");readonly relationship=signal("");readonly status=signal("");readonly outstanding=signal("");readonly lastVisit=signal("");readonly selected=signal<OwnerClient|null>(null);readonly detail=signal<OwnerClientDetail|null>(null);readonly detailLoading=signal(false);readonly detailError=signal("");
  private requestId=0;private detailRequestId=0;private timer?:ReturnType<typeof setTimeout>;private trigger:HTMLElement|null=null;
  constructor(private owner:OwnerAppService,readonly context:OwnerContextService,route:ActivatedRoute){const query=route.snapshot.queryParamMap;const relationship=query.get("relationship")||query.get("clientState");if(relationship==="new"||relationship==="returning")this.relationship.set(relationship);const search=query.get("search")||query.get("id")||"";this.search.set(search);this.debouncedSearch.set(search);effect(()=>{const branch=this.context.selectedBranchId();const range=this.context.periodRange();untracked(()=>{void branch;void range;this.items.set([]);this.page.set(null);this.metadata.set(null);this.close(false);void this.load();});});}
  ngOnDestroy(){if(this.timer)clearTimeout(this.timer);this.requestId++;this.detailRequestId++;document.documentElement.classList.remove("staff-overlay-open");}
  searchChanged(value:string){this.search.set(value);if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>{this.debouncedSearch.set(value.trim());this.items.set([]);this.page.set(null);void this.load();},350);} clearSearch(){this.search.set("");this.debouncedSearch.set("");this.items.set([]);this.page.set(null);void this.load();} filtersChanged(){this.items.set([]);this.page.set(null);void this.load();}
  async load(){const request=++this.requestId;this.loading.set(true);this.refreshError.set("");const had=this.items().length>0;try{const range=this.context.periodRange();const result=await this.owner.ownerClients({branchId:this.context.selectedBranchId()||"all",page:this.page()?.page||1,pageSize:30,search:this.debouncedSearch(),relationship:this.relationship(),status:this.status(),outstanding:this.outstanding(),lastVisit:this.lastVisit(),from:range.start,to:range.end});if(request!==this.requestId)return;this.items.set(result.items);this.page.set(result.page);this.metadata.set(result.metadata);this.blockingError.set("");this.context.markSuccessfulRefresh();}catch{if(request!==this.requestId)return;if(had)this.refreshError.set("Refresh failed. Previously loaded clients remain visible.");else this.blockingError.set("Aura could not load clients for this owner scope.");}finally{if(request===this.requestId)this.loading.set(false);}}
  go(delta:number){const p=this.page();if(!p)return;this.items.set([]);this.page.set({...p,page:p.page+delta});void this.load();} resetFilters(){this.relationship.set("");this.status.set("");this.outstanding.set("");this.lastVisit.set("");this.clearSearch();}
  async open(client:OwnerClient,event:Event){this.trigger=event.currentTarget as HTMLElement;this.selected.set(client);this.detail.set(null);this.detailError.set("");this.detailLoading.set(true);document.documentElement.classList.add("staff-overlay-open");setTimeout(()=>this.drawer?.nativeElement.focus());const request=++this.detailRequestId;try{const result=await this.owner.ownerClient(client.id,this.context.selectedBranchId()||"all");if(request===this.detailRequestId)this.detail.set(result);}catch{if(request===this.detailRequestId)this.detailError.set("The saved profile could not be loaded. Try again.");}finally{if(request===this.detailRequestId)this.detailLoading.set(false);}}
  close(restoreFocus=true){this.detailRequestId++;this.selected.set(null);this.detail.set(null);document.documentElement.classList.remove("staff-overlay-open");if(restoreFocus)setTimeout(()=>this.trigger?.focus());}
  @HostListener("window:keydown",["$event"]) keydown(event:KeyboardEvent){if(!this.selected())return;if(event.key==="Escape"){event.preventDefault();this.close();return;}if(event.key!=="Tab")return;const nodes=this.drawer?.nativeElement.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  maskedContact(client:Pick<OwnerClient,"phone"|"email">){const phone=client.phone?`•••• ${client.phone.replace(/\D/g,"").slice(-4)}`:"No phone";return client.email?`${phone} · ${client.email.replace(/^(.).+(@.*)$/,"$1•••$2")}`:phone;} date(value:string){return this.context.formatDate(value);} dateTime(value:string){return this.context.formatDateTime(value);}
}
