import { CommonModule } from "@angular/common";
import { Component, HostListener, OnInit, computed, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { OwnerAppService } from "./owner-app.service";
import { OwnerContextService } from "./owner-context.service";
import { OwnerGeneralSettings, OwnerSettingsResponse, OwnerWhatsAppConnection, OwnerWhatsAppStatus } from "./owner-administration.models";

declare global { interface Window { FB?: { init(input: Record<string, unknown>): void; login(callback: (response: { authResponse?: { code?: string } }) => void, options: Record<string, unknown>): void }; fbAsyncInit?: () => void; } }

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<article class="adm-page" [attr.aria-busy]="loading()">
  <header class="adm-hero"><div><p class="adm-eyebrow">Administration · General settings</p><h1>One workspace, thoughtfully configured.</h1><p>Only fields supported by the existing general settings contract are editable. Specialist settings remain with their authoritative modules.</p></div><div class="adm-actions"><label class="adm-field">Settings scope<select [ngModel]="scope()" (ngModelChange)="changeScope($event)" [disabled]="loading()||saving()"><option value="">All branches</option>@for(branch of context.branches();track branch.id){<option [value]="branch.id">{{branch.name}}</option>}</select></label>@if(!error()||response()){<button class="adm-button" [disabled]="loading()||saving()" (click)="reload()">↻ Reload</button>}</div></header>
  @if(message()){<p class="adm-message" [class.error]="messageError()" [attr.role]="messageError()?'alert':'status'">{{message()}}</p>}
  @if(loading()&&!response()){<div class="adm-skeleton"><i></i><i></i><i></i></div>}@else if(error()&&!response()){<section class="adm-state" role="alert"><span>!</span><h2>Settings unavailable</h2><p>{{error()}}</p><button class="adm-button" (click)="load()">Try again</button></section>}@else if(draft();as settings){
   <section class="adm-settings"><nav class="adm-section-nav" aria-label="Settings sections"><a href="/owner/settings#business">Business profile</a><a href="/owner/settings#whatsapp">WhatsApp</a><a href="/owner/settings#regional">Regional & time</a><a href="/owner/settings#branches">Branch behavior</a><a href="/owner/settings#interface">Interface</a><a href="/owner/settings#defaults">Owner defaults</a><a href="/owner/settings#availability">Availability</a></nav>
   <div class="adm-settings-body">
     <section class="adm-settings-section" id="business"><header><h2>Business profile</h2><p>Workspace identity and landing behavior from the general settings contract.</p></header><div class="adm-setting-grid"><label class="adm-field">Workspace name<input [(ngModel)]="settings.workspace.workspaceName" (ngModelChange)="changed()" maxlength="120" [attr.aria-invalid]="validation().workspaceName"></label><label class="adm-field">Default landing page<select [(ngModel)]="settings.workspace.defaultLandingPage" (ngModelChange)="changed()"><option value="dashboard">Dashboard</option><option value="pos">Billing Access</option><option value="appointments">Appointments</option><option value="clients">Clients</option><option value="reports">Reports</option></select></label><label class="adm-switch">Fast POS enabled<input type="checkbox" [(ngModel)]="settings.workspace.fastPosEnabled" (ngModelChange)="changed()"></label></div><p class="adm-error" *ngIf="validation().workspaceName">Workspace name is required.</p></section>
     <section class="adm-settings-section" id="whatsapp"><header><h2>WhatsApp</h2><p>Connect this salon's own WhatsApp Business Account. Tokens stay on the server and are never shown here.</p></header>@if(whatsappLoading()){<p>Loading WhatsApp status…</p>}@else if(whatsappError()){<p class="adm-error">{{whatsappError()}}</p>}@else{<div class="adm-setting-grid"><div><strong>Status</strong><p>{{primaryWhatsApp()?.status==='connected'?'Connected ✓':'Not connected'}}</p></div>@if(primaryWhatsApp();as wa){<div><strong>Business</strong><p>{{wa.verifiedName||'Meta business'}}</p></div><div><strong>Number</strong><p>{{wa.displayPhoneNumber||'Not available'}}</p></div><div><strong>WhatsApp Business Account</strong><p>{{wa.wabaId}}</p></div><div><strong>Phone Number ID</strong><p>{{wa.phoneNumberId}}</p></div><div><strong>Connected</strong><p>{{wa.connectedAt?date(wa.connectedAt):'Not connected'}}</p></div>}</div><div class="adm-actions" style="margin-top:1rem"><button class="adm-button primary" type="button" [disabled]="whatsappBusy()" (click)="connectWhatsApp()">{{primaryWhatsApp()?.status==='connected'?'Reconnect':'Connect WhatsApp'}}</button><button class="adm-button" type="button" [disabled]="whatsappBusy()" (click)="loadWhatsApp(true)">Test Connection</button>@if(primaryWhatsApp()?.status==='connected'){<button class="adm-button" type="button" [disabled]="whatsappBusy()" (click)="disconnectWhatsApp()">Disconnect</button>}</div>@if(!whatsappStatus()?.configured){<p class="adm-error">Meta Embedded Signup is not configured on this environment yet. Set META_APP_ID, META_CONFIG_ID and related backend secrets first.</p>}}</section>
     <section class="adm-settings-section" id="regional"><header><h2>Regional, date & time</h2><p>Timezone and formatting remain explicit; business dates use the configured timezone.</p></header><div class="adm-setting-grid"><label class="adm-field">Country<input [(ngModel)]="settings.localization.country" (ngModelChange)="changed()"></label><label class="adm-field">Language<input [(ngModel)]="settings.localization.language" (ngModelChange)="changed()"></label><label class="adm-field">Timezone<input [(ngModel)]="settings.localization.timezone" (ngModelChange)="changed()" placeholder="Asia/Kolkata" [attr.aria-invalid]="validation().timezone"></label><label class="adm-field">Currency<input [(ngModel)]="settings.localization.currency" (ngModelChange)="changed()" maxlength="3"></label><label class="adm-field">Locale<input [(ngModel)]="settings.localization.locale" (ngModelChange)="changed()"></label><label class="adm-field">Date format<select [(ngModel)]="settings.dateTime.dateFormat" (ngModelChange)="changed()"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label class="adm-field">Time format<select [(ngModel)]="settings.dateTime.timeFormat" (ngModelChange)="changed()"><option value="12h">12 hour</option><option value="24h">24 hour</option></select></label><label class="adm-field">Week starts on<select [(ngModel)]="settings.dateTime.weekStartsOn" (ngModelChange)="changed()"><option>Monday</option><option>Sunday</option></select></label><label class="adm-field">Business day starts<input type="number" min="0" max="23" [(ngModel)]="settings.dateTime.businessDayStartHour" (ngModelChange)="changed()" [attr.aria-invalid]="validation().businessHour"></label></div><p class="adm-error" *ngIf="validation().timezone">Enter an IANA timezone such as Asia/Kolkata.</p><p class="adm-error" *ngIf="validation().businessHour">Business day start must be a whole hour from 0 to 23.</p></section>
    <section class="adm-settings-section" id="branches"><header><h2>Branch behavior</h2><p>Controls selection behavior only; backend branch assignments remain authoritative.</p></header><div class="adm-setting-grid"><label class="adm-switch">Remember last branch<input type="checkbox" [(ngModel)]="settings.branchBehavior.rememberLastBranch" (ngModelChange)="changed()"></label><label class="adm-switch">Require branch selection<input type="checkbox" [(ngModel)]="settings.branchBehavior.requireBranchSelection" (ngModelChange)="changed()"></label><label class="adm-switch">Allow branch switch<input type="checkbox" [(ngModel)]="settings.branchBehavior.allowBranchSwitch" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="interface"><header><h2>Interface</h2><p>General workspace presentation supported by the current contract.</p></header><div class="adm-setting-grid"><label class="adm-switch">Compact mode<input type="checkbox" [(ngModel)]="settings.interface.compactMode" (ngModelChange)="changed()"></label><label class="adm-switch">Show module badges<input type="checkbox" [(ngModel)]="settings.interface.showModuleBadges" (ngModelChange)="changed()"></label><label class="adm-switch">Enable command search<input type="checkbox" [(ngModel)]="settings.interface.enableCommandSearch" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="defaults"><header><h2>Owner defaults</h2><p>Saved defaults from the general settings contract.</p></header><div class="adm-setting-grid"><label class="adm-switch">Refresh reports on open<input type="checkbox" [(ngModel)]="settings.defaults.refreshReportsOnOpen" (ngModelChange)="changed()"></label><label class="adm-switch">Owner notifications<input type="checkbox" [(ngModel)]="settings.defaults.ownerNotifications" (ngModelChange)="changed()"></label><label class="adm-switch">Staff hints<input type="checkbox" [(ngModel)]="settings.defaults.staffHints" (ngModelChange)="changed()"></label></div></section>
    <section class="adm-settings-section" id="availability"><header><h2>Specialist settings</h2><p>These areas are not presented as editable because another backend contract owns them.</p></header><div class="adm-capabilities">@for(item of unavailable();track item.key){<div><strong>{{label(item.key)}}</strong><p>{{item.value}}</p></div>}</div></section>
    <div class="adm-sticky-save"><span>@if(dirty()){<strong>Unsaved changes</strong> · Leave protection is active.}@else if(response()?.audit?.lastChangedAt){Saved {{date(response()!.audit.lastChangedAt)}} by {{response()!.audit.lastChangedBy}}}@else{No saved changes recorded.}</span><div class="adm-actions"><button class="adm-button" [disabled]="!dirty()||saving()" (click)="discard()">Discard</button><button class="adm-button primary" [disabled]="!dirty()||saving()||invalid()" (click)="save()">{{saving()?'Saving…':'Save settings'}}</button></div></div>
  </div></section>}
</article>
`,styleUrls:["./owner-shell.styles.css","./owner-administration.css"]})
export class OwnerSettingsPage implements OnInit{
  readonly loading=signal(true);readonly saving=signal(false);readonly error=signal("");readonly message=signal("");readonly messageError=signal(false);readonly scope=signal("");readonly response=signal<OwnerSettingsResponse|null>(null);readonly draft=signal<OwnerGeneralSettings|null>(null);readonly baseline=signal("");readonly whatsappStatus=signal<OwnerWhatsAppStatus|null>(null);readonly whatsappLoading=signal(false);readonly whatsappBusy=signal(false);readonly whatsappError=signal("");
  private request=0;
  readonly dirty=computed(()=>!!this.draft()&&JSON.stringify(this.draft())!==this.baseline());readonly validation=computed(()=>{const s=this.draft();return{workspaceName:!s?.workspace.workspaceName.trim(),timezone:!!s&&!/^[A-Za-z_]+\/[A-Za-z_+-]+(?:\/[A-Za-z_+-]+)?$/.test(s.localization.timezone),businessHour:!!s&&(!Number.isInteger(Number(s.dateTime.businessDayStartHour))||Number(s.dateTime.businessDayStartHour)<0||Number(s.dateTime.businessDayStartHour)>23)}});readonly invalid=computed(()=>Object.values(this.validation()).some(Boolean));readonly unavailable=computed(()=>Object.entries(this.response()?.unavailableSections||{}).map(([key,value])=>({key,value})));readonly primaryWhatsApp=computed<OwnerWhatsAppConnection|null>(()=>this.whatsappStatus()?.connections?.[0]||null);
  constructor(private readonly api:OwnerAppService,readonly context:OwnerContextService){}ngOnInit(){this.scope.set(this.context.selectedBranchId());void this.load();void this.loadWhatsApp();}
  async load(){const request=++this.request,scope=this.scope();this.loading.set(true);this.error.set("");try{const data=await this.api.administrationSettings(scope);if(request===this.request&&scope===this.scope()){this.response.set(data);this.setDraft(data.settings);}}catch{if(request===this.request)this.error.set("Solastio could not load general settings for this scope.");}finally{if(request===this.request)this.loading.set(false);}}
  reload(){if(this.dirty()&&!confirm("Discard unsaved settings and reload the saved version?"))return;void this.load();}
  changeScope(value:string){if(this.dirty()&&!confirm("Discard unsaved settings before changing scope?"))return;this.scope.set(value);this.message.set("");void this.load();}
  changed(){const value=this.draft();if(value)this.draft.set(structuredClone(value));}
  discard(){const settings=this.response()?.settings;if(settings)this.setDraft(settings);this.message.set("Unsaved changes discarded.");this.messageError.set(false);}
   async save(){const settings=this.draft(),scope=this.scope();if(!settings||!this.dirty()||this.invalid()||this.saving())return;this.saving.set(true);this.message.set("");try{const data=await this.api.saveAdministrationSettings(scope,settings);this.response.set({...data,supportedSections:this.response()?.supportedSections||[],unavailableSections:this.response()?.unavailableSections||{}});this.setDraft(data.settings);if(scope===this.context.selectedBranchId())this.context.applySettings(data.settings);this.messageError.set(false);this.message.set(data.preservedUnknownSettings?"Settings saved. Unrecognized stored settings were preserved.":"Settings saved.");}catch{this.messageError.set(true);this.message.set("Settings were not saved. Review the fields or retry after refreshing.");}finally{this.saving.set(false);}}
  canLeave(){return!this.dirty()||confirm("You have unsaved general settings. Leave without saving?");}
  async loadWhatsApp(background=false){if(!background)this.whatsappLoading.set(true);this.whatsappError.set("");try{this.whatsappStatus.set(await this.api.whatsappStatus());if(background){this.messageError.set(false);this.message.set("WhatsApp status refreshed.");}}catch{this.whatsappError.set("WhatsApp connection status could not be loaded.");}finally{this.whatsappLoading.set(false);}}
  async connectWhatsApp(){if(this.whatsappBusy())return;this.whatsappBusy.set(true);this.message.set("");try{const signup=await this.api.whatsappSignupState();await this.loadFacebookSdk(signup.appId,signup.apiVersion);await new Promise<void>((resolve,reject)=>{window.FB!.login(async(response)=>{const code=response.authResponse?.code;if(!code){reject(new Error("Meta did not return an authorization code."));return;}try{await this.api.whatsappSignupCallback({state:signup.state,authorizationCode:code});await this.loadWhatsApp();this.messageError.set(false);this.message.set("WhatsApp connected successfully.");resolve();}catch(error){reject(error);}}, {config_id: signup.configId, response_type: "code", override_default_response_type: true, extras: {setup: {}, featureType: "whatsapp_embedded_signup"}});});}catch(error){this.messageError.set(true);this.message.set(error instanceof Error?error.message:"WhatsApp connection could not be completed.");}finally{this.whatsappBusy.set(false);}}
  async disconnectWhatsApp(){const current=this.primaryWhatsApp();if(!current||this.whatsappBusy()||!confirm("Disconnect WhatsApp for this salon? Historical customers and appointments will remain."))return;this.whatsappBusy.set(true);try{await this.api.disconnectWhatsApp(current.phoneNumberId);await this.loadWhatsApp();this.messageError.set(false);this.message.set("WhatsApp disconnected. Outbound messages are stopped for this number.");}catch{this.messageError.set(true);this.message.set("WhatsApp could not be disconnected. Try again.");}finally{this.whatsappBusy.set(false);}}
  private loadFacebookSdk(appId:string,apiVersion:string){return new Promise<void>((resolve,reject)=>{if(window.FB){resolve();return;}window.fbAsyncInit=()=>{try{window.FB!.init({appId,autoLogAppEvents:true,xfbml:false,version:apiVersion});resolve();}catch(error){reject(error);}};const existing=document.getElementById("facebook-jssdk");if(existing)return;const script=document.createElement("script");script.id="facebook-jssdk";script.async=true;script.defer=true;script.crossOrigin="anonymous";script.src="https://connect.facebook.net/en_US/sdk.js";script.onerror=()=>reject(new Error("Could not load Meta SDK."));document.body.appendChild(script);});}
  @HostListener("window:beforeunload",["$event"])beforeUnload(event:BeforeUnloadEvent){if(!this.dirty())return;event.preventDefault();event.returnValue="";}
  private setDraft(settings:OwnerGeneralSettings){const copy=structuredClone(settings);this.draft.set(copy);this.baseline.set(JSON.stringify(copy));}
  label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}date(value:string){return this.context.formatDateTime(value);}
}
